In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/split_assignment.tsv
/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/Documentation_template.md
/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/README.md
/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/utils/validate_submission.py
/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/test/test_source2.tsv
/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/test/test_source3.tsv
/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/test/test_source1.tsv
/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_ground_truth.tsv
/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source3.tsv
/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source2.tsv
/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source1.tsv

In [4]:
from pathlib import Path

BASE = Path(
    "/kaggle/input/datasets/lakshaygauniyal/"
    "amazon-ml-2026-dataset/"
    "6ab10eb3b23ba_student_resource/student_resource"
)

TRAIN_DIR = BASE / "dataset" / "train"
TEST_DIR = BASE / "dataset" / "test"

SOURCE1_TRAIN = TRAIN_DIR / "train_source1.tsv"
SOURCE2_TRAIN = TRAIN_DIR / "train_source2.tsv"
SOURCE3_TRAIN = TRAIN_DIR / "train_source3.tsv"

SOURCE1_TEST = TEST_DIR / "test_source1.tsv"
SOURCE2_TEST = TEST_DIR / "test_source2.tsv"
SOURCE3_TEST = TEST_DIR / "test_source3.tsv"

print(SOURCE1_TRAIN)

/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source1.tsv

In [5]:
s1_sample = pd.read_csv(
    SOURCE1_TRAIN,
    sep="\t",
    nrows=10
)

s2_sample = pd.read_csv(
    SOURCE2_TRAIN,
    sep="\t",
    nrows=10
)

s3_sample = pd.read_csv(
    SOURCE3_TRAIN,
    sep="\t",
    nrows=10
)

print("S1 columns:")
print(s1_sample.columns.tolist())

print("\nS2 columns:")
print(s2_sample.columns.tolist())

print("\nS3 columns:")
print(s3_sample.columns.tolist())

S1 columns:
['entity_id', 'business_name', 'business_address', 'country']

S2 columns:
['entity_id', 'business_name', 'business_address', 'country']

S3 columns:
['entity_id', 'business_name', 'business_address', 'country']

In [6]:
display(s1_sample)

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India
5,S1-851869949,Custom Wealth Services LLC,"OH, Columbus, 5559 Orville Avenue",US
6,S1-785847572,Consulting Nyasa Nursing Private Limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",India
7,S1-27541239,Nexus Anchor Rain,"1111 Church Street, Unit 2007, Nashville, TN",US
8,S1-629417405,Moore Bitwise Inc,"337 Oakland Avenue, Michigan City, IN",US
9,S1-22305073,Dermatology Green Medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",US

In [7]:
display(s2_sample)

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US
5,S2-138046867,Lee and Lawson,"1702 Pine Avenue, CITY OF MENOMONIE, WI",US
6,S2-584977605,SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPOR...,"H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab",India
7,S2-277444929,Shree Infracon Private Ltd,"63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKH...",India
8,S2-721031885,Chavira Platinum Chimera LLC,"282 SAXONY DRIVE, FTT MITCHELL, KY",US
9,S2-508602797,FOUNDATION EXCEL AGENCY PRIVATE LIMITED,"HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, M...",India

In [8]:
display(s3_sample)

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India
5,S3-578159284,LLC Hernandez Colonial Redwood,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...",US
6,S3-121412624,Classic Equity Partners Group,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...",US
7,S3-249416830,Ectolumdrex dba X+ Madison Inc,"S03575 Cty Tk M, Town Of Buffalo, WI",US
8,S3-107644605,Animal Hanisch Hospirlg,"##8 Willow Oak Lane, Fl. 0, Saint Louis, Missouri",US
9,S3-160217003,Gomez Optimal,"343 Hempstead 161, Hope, Arkansas",US

In [9]:
print(s1_sample.isna().sum())
print(s2_sample.isna().sum())
print(s3_sample.isna().sum())

entity_id           0
business_name       0
business_address    0
country             0
dtype: int64
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64
entity_id           0
business_name       0
business_address    1
country             0
dtype: int64

In [10]:
import pandas as pd
import re
from pathlib import Path

def sample_tsv(path, n=5000, chunksize=100_000, random_state=42):
    """
    Sample approximately n rows from a large TSV without loading
    the complete file into memory.
    """
    samples = []

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=chunksize
    ):
        take = min(len(chunk), max(1, n // 10))

        samples.append(
            chunk.sample(
                n=take,
                random_state=random_state
            )
        )

        if sum(len(x) for x in samples) >= n:
            break

    result = pd.concat(samples, ignore_index=True)

    if len(result) > n:
        result = result.sample(
            n=n,
            random_state=random_state
        ).reset_index(drop=True)

    return result

In [11]:
s1_explore = sample_tsv(SOURCE1_TRAIN, n=5000)
s2_explore = sample_tsv(SOURCE2_TRAIN, n=5000)
s3_explore = sample_tsv(SOURCE3_TRAIN, n=5000)

test_s1_explore = sample_tsv(SOURCE1_TEST, n=5000)
test_s2_explore = sample_tsv(SOURCE2_TEST, n=5000)
test_s3_explore = sample_tsv(SOURCE3_TEST, n=5000)

In [12]:
for name, df in {
    "S1 train": s1_explore,
    "S2 train": s2_explore,
    "S3 train": s3_explore,
    "S1 test": test_s1_explore,
    "S2 test": test_s2_explore,
    "S3 test": test_s3_explore,
}.items():
    
    print("\n", "=" * 50)
    print(name)
    print("=" * 50)
    print(df["country"].value_counts(dropna=False))

 ==================================================
S1 train
==================================================
country
US       2937
India    2063
Name: count, dtype: int64

 ==================================================
S2 train
==================================================
country
US       3008
India    1992
Name: count, dtype: int64

 ==================================================
S3 train
==================================================
country
US       3003
India    1997
Name: count, dtype: int64

 ==================================================
S1 test
==================================================
country
India     2362
US        1894
France     744
Name: count, dtype: int64

 ==================================================
S2 test
==================================================
country
India     2443
US        1851
France     706
Name: count, dtype: int64

 ==================================================
S3 test
==================================================
country
India     2381
US        1905
France     714
Name: count, dtype: int64

In [13]:
france_s1 = test_s1_explore[
    test_s1_explore["country"].astype(str).str.lower() == "france"
]

france_s2 = test_s2_explore[
    test_s2_explore["country"].astype(str).str.lower() == "france"
]

france_s3 = test_s3_explore[
    test_s3_explore["country"].astype(str).str.lower() == "france"
]

print("France S1:", len(france_s1))
print("France S2:", len(france_s2))
print("France S3:", len(france_s3))

display(
    france_s1[
        ["business_name", "business_address"]
    ].head(20)
)

display(
    france_s2[
        ["business_name", "business_address"]
    ].head(20)
)

France S1: 744
France S2: 706
France S3: 714

,business_name,business_address
1,Ets Competences SAS,"Nouvelle-Aquitaine, Lège-Cap-Ferret, 13 Rue He..."
3,Valorisation (France) Theatre SAS,"La Teste-de-Buch, 10 Allée Francois Rabelais, ..."
20,Guilde Comite (France) EURL,"7 Rue Masséna, Dunkerque, Hauts-de-France"
23,Familles Maison SARL,"13 Rue Fermat, Lille, Hauts-de-France"
34,KLM Culturelle SASU,"Hauts-de-France, Roubaix, 59 Rue Daubenton"
42,MPR Ecole SARL,"7 Route de Vertou, Nantes, Pays de la Loire"
43,Pornic Primaire SA,"Pays de la Loire, Pornic, 17 Rue des Sables"
46,Comité de Clemence,"31 Rue Archimède, Roubaix, Hauts-de-France"
49,Radio Comite EURL,"76 Rue Jean Bart, Saint-Nazaire, Pays de la Loire"
50,Prudence & Cie SASU,"57 Rue Goya, Bordeaux, Nouvelle-Aquitaine"
58,Qi Federation (France) SAS,"Lille, 59160 LILLE, 43 rue Eugène Varlin, Haut..."
64,EHPAD de Jean,"262 Bis Boulevard du Massacre, Saint-Herblain,..."
74,Club des Chasse,"129 Rue Victor Hugo, Lille, Hauts-de-France"
87,Mission (France) Club SARL,"Hauts-de-France, Tourcoing, 64 Rue des Phalempins"
88,Cantonal Culture SA,"15 A Rue Xavier Arnozan, Pessac, Nouvelle-Aqui..."
104,Maison de Santé de la Jean,"Pays de la Loire, 1 Allée de Bannalec, Nantes"
119,Dunkerque Culturel SARL,"6 Rue de l'Écluse de Bergues, Dunkerque, Hauts..."
126,Morieres Groupe SARL,"1 Rue Caumartin, Lille, Hauts-de-France"
128,Clinique du Georges,"Hauts-de-France, Roubaix, 17 RUE du noueau monde"
144,Extreme & Fils SAS,"200 bis Rue de la Benauge, Bordeaux, Nouvelle-..."

,business_name,business_address
4,CITE COMPAGNIE EURL,"20 AVENUE DE SAINT-MEDARD, MÉRIGNAC"
5,Girard The Institut SAS,"Pays de la Loire, 17 AVENUE DE LA LAVANDE, LA ..."
9,Access Amicale Sarl,"Nouvelle-Aquitaine, 42 R FRATNZ MALVEZIN, BORD..."
29,Luna (France) Lycée SNC,"29 IMP. CHARLIE CHAPLIN, SAINT-HERBLAIN"
38,LYCÉE PROMOTION GROUPE,"(5) CHEMIN DE L'HÉRAULT, ST-HERBLAIN"
40,PETITS AMIS,"NO. 34 RUE JULES LANERY, DUNKERQUE, Nord"
41,Retraites Pàtrimoine SCI,"29 BIS R. PETITE BIESSE, NANTES"
50,Fédération du [Lecole],"54 RUE LA PEROUSE, TOURCOING, Hauts-de-France"
56,Ressortissants Ànciens EURL,"181 BD BROODCOORENS, SAINT-NAZAIRE"
58,Salopettes (France) Sôciete Groupe SARL,"8 RUE SAINT STANISLAS, NANTES, Pays de la Loire"
71,Chemin Petit Lycée Sas,NaN
83,CALAIS SPORT DISTRIBUTION,"Pas-de-Calais, 58 - RUE LEAVERS, CALAIS"
87,Eglise Cb SAS,"20 B RUE DES BOUCHERS, LILLE, Nord"
89,Lycée du Sainte SCI,"24 R JEAN MERMOZ, NANTES, Pays de la Loire"
90,Team Ecole SA,"NO 41 BOULEVARD DU HAUT LIVRAC, PESSAC, Gironde"
97,Club de Familles et Associés,"NO 38 R FAMATINA, BORDEAUX, Nouvelle-Aquitaine"
104,SARL Afrd Lyçee,"8 R SAINT GOHARD, Nantes"
108,LAFFICHE et CIE S.N.C.,"37 R. PUAL DUKAS, MÉRIGNAC"
109,Amities College,"12 RUE DE LA FONTAINE CARON, NANTES, Loire-Atl..."
110,ouest centre sarl,"NO 3 BD LELASSEUR, NANTES, Loire-Atlantique"

In [14]:
combined_explore = pd.concat(
    [
        s1_explore.assign(source="S1"),
        s2_explore.assign(source="S2"),
        s3_explore.assign(source="S3")
    ],
    ignore_index=True
)

In [15]:
patterns = {
    "Pvt": r"\bpvt\.?\b",
    "Ltd": r"\bltd\.?\b",
    "Corp": r"\bcorp\.?\b",
    "Inc": r"\binc\.?\b",
    "LLC": r"\bllc\b",
    "St": r"\bst\.?\b",
    "Rd": r"\brd\.?\b",
}

In [16]:
for name, pattern in patterns.items():
    name_matches = combined_explore[
        combined_explore["business_name"]
        .astype("string")
        .str.contains(pattern, case=False, regex=True, na=False)
    ]

    address_matches = combined_explore[
        combined_explore["business_address"]
        .astype("string")
        .str.contains(pattern, case=False, regex=True, na=False)
    ]

    print(
        f"{name:6s} | "
        f"name={len(name_matches):5d} | "
        f"address={len(address_matches):5d}"
    )

Pvt    | name=  738 | address=    9
Ltd    | name= 1199 | address=   47
Corp   | name=  344 | address=    7
Inc    | name= 1344 | address=    0
LLC    | name= 1873 | address=    0
St     | name=   19 | address=  672
Rd     | name=    0 | address=  659

In [17]:
for col in ["business_name", "business_address"]:
    count = combined_explore[col].astype("string").str.contains(
        "&",
        regex=False,
        na=False
    ).sum()

    print(col, "contains &:", count)

business_name contains &: 654
business_address contains &: 141

In [18]:
amp_examples = combined_explore[
    combined_explore["business_name"]
    .astype("string")
    .str.contains("&", regex=False, na=False)
]

display(
    amp_examples[
        ["business_name", "business_address", "country"]
    ].head(20)
)

,business_name,business_address,country
24,"Colburn, Shannon & Buzzard","517 100, Milford, UT",US
33,Gram & Brothers Pvt. Ltd.,"Adarsh Nagar, Parbhani, Pathri, Maharashtra, C...",India
34,"Jones, Alarcon & Perez LLC","5 Buffalo Run, Southborough, MA",US
46,Foot & Ankle Care,"1970 Hogue Road, Clarksville, TN",US
86,"W E & G South, Inc","Katy, 1147 Rennie Drive, TX",US
116,T & N Resilience LLC,"6426 Royal Pines Place, Lino Lakes, MN",US
121,Sitaram & Brothers Private Limited,"House No 169 2Nd Floor Bl, Gujrawala Town Ph 1...",India
134,"Thornton, Mckay & Wolf Bioworks LLC","208 Gleed Lane, Lima, MT",US
173,Capitol & Brothers Private Limited,"Maharashtra, S No 21/2Pune Satar Road, Sawant ...",India
192,W & G Motors Inc,"1206 Alpine Circle, Green Valley, AZ",US
240,Ramraj & Partners Limited,"8/120, Puthumana Illam Komana, Ambalapuzha Po,...",India
312,"Carr, Hernandez & Garner Inc.","304 Waco Avenue, Unit Apt A, Russellville, AR",US
322,"Portales, Cameron & Johnson Nexera","183 Heights Boulevard, Houston, TX",US
323,"Wright, Vasques & Hall Apartment Inc.","5 Manhattan Avenue, NY, Westbury",US
350,Khan & Hicks Imperii Inc.,"5578 Bracken Drive, Indianapolis, IN",US
352,Keynote & Brothers,"Themillenia, Tower-B, Level11-14, No.1&2Murphy...",India
364,Mad & Co,"B - 109, Gopal Palace, Opp. Ashian Park Nehrun...",India
373,Bluemoon & Co,"254 Lakhani Bigha, Sarvayoni City, Dinapur-Cum...",India
390,Rice & Geist LLC,"4619 Vernon Avenue, Phoenix, AZ",US
411,Maa & Associates,"D/15, Naik Nagar Chs., S.G Barve Marg Shivshri...",India

In [19]:
from collections import Counter

punctuation_counter = Counter()

for text in combined_explore["business_name"].dropna().astype(str):
    for ch in text:
        if not ch.isalnum() and not ch.isspace():
            punctuation_counter[ch] += 1

print(punctuation_counter.most_common(30))

[('.', 2742), (',', 1379), ('्', 1086), ('ि', 849), ('े', 818), ('&', 657), ('-', 635), ('(', 628), (')', 626), ('ा', 501), ('్', 432), ('್', 400), ('்', 333), ('[', 284), (']', 284), ("'", 265), ('ं', 241), ('ி', 197), ('ी', 178), ('്', 172), ('ి', 164), ('ಿ', 155), ('્', 149), ('/', 137), ('ি', 124), ('ो', 121), ('*', 117), ('্', 104), ('া', 96), ('ে', 95)]

In [20]:
from collections import Counter

punctuation_counter = Counter()

for text in combined_explore["business_name"].dropna().astype(str):
    for ch in text:
        if not ch.isalnum() and not ch.isspace():
            punctuation_counter[ch] += 1

print(punctuation_counter.most_common(30))

[('.', 2742), (',', 1379), ('्', 1086), ('ि', 849), ('े', 818), ('&', 657), ('-', 635), ('(', 628), (')', 626), ('ा', 501), ('్', 432), ('್', 400), ('்', 333), ('[', 284), (']', 284), ("'", 265), ('ं', 241), ('ி', 197), ('ी', 178), ('്', 172), ('ి', 164), ('ಿ', 155), ('્', 149), ('/', 137), ('ি', 124), ('ो', 121), ('*', 117), ('্', 104), ('া', 96), ('ে', 95)]

In [21]:
for name, df in {
    "S1": s1_explore,
    "S2": s2_explore,
    "S3": s3_explore
}.items():

    print("\n", name)

    print(
        df[
            ["business_name", "business_address", "country"]
        ].isna().sum()
    )

 S1
business_name       0
business_address    0
country             0
dtype: int64

 S2
business_name         0
business_address    170
country               0
dtype: int64

 S3
business_name         0
business_address    162
country               0
dtype: int64

In [22]:
for name, df in {
    "S1": s1_explore,
    "S2": s2_explore,
    "S3": s3_explore
}.items():

    print("\n", name)

    for col in ["business_name", "business_address"]:
        empty = (
            df[col]
            .fillna("")
            .astype(str)
            .str.strip()
            .eq("")
            .sum()
        )

        print(col, "empty:", empty)

 S1
business_name empty: 0
business_address empty: 0

 S2
business_name empty: 0
business_address empty: 170

 S3
business_name empty: 0
business_address empty: 162

# PREPROCESSING

In [84]:
import os

os.makedirs("/kaggle/working/src", exist_ok=True)

print(os.listdir("/kaggle/working"))

['abbreviations_production.json', 'src', 'abbreviations.json', '.virtual_documents']

In [87]:
import os

preprocess_path = "/kaggle/working/src/preprocess.py"

# Remove the existing dummy file
if os.path.exists(preprocess_path):
    os.remove(preprocess_path)

print("Removed:", preprocess_path)
print("Exists now:", os.path.exists(preprocess_path))

Removed: /kaggle/working/src/preprocess.py
Exists now: False

#  imports + normalize_unicode()

In [88]:
%%writefile -a /kaggle/working/src/preprocess.py

import re
import unicodedata


def normalize_unicode(text):
    """
    Normalize Unicode text while preserving non-ASCII characters.

    Handles:
    - None / missing values
    - Unicode compatibility normalization (NFKC)
    - Leading/trailing whitespace
    - Repeated whitespace
    """

    if text is None:
        return ""

    text = str(text)

    # Normalize Unicode while preserving characters such as
    # Hindi, French accents, etc.
    text = unicodedata.normalize("NFKC", text)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

Writing /kaggle/working/src/preprocess.py

In [89]:
import os

print("src exists:", os.path.exists("/kaggle/working/src"))
print("preprocess.py exists:", os.path.exists("/kaggle/working/src/preprocess.py"))

print("\nFiles inside src:")
print(os.listdir("/kaggle/working/src"))

src exists: True
preprocess.py exists: True

Files inside src:
['preprocess.py']

# test c1

In [27]:
from importlib import reload
import sys

sys.path.append("/kaggle/working")

import src.preprocess as preprocess
reload(preprocess)

tests = [
    "  École   de   Santé  ",
    "राम मार्केटिंग प्राइवेट लिमिटेड",
    "Lège-Cap-Ferret",
    None,
    "   2100   Cameron   Drive   "
]

for text in tests:
    print(repr(text), "→", repr(preprocess.normalize_unicode(text)))

'  École   de   Santé  ' → 'École de Santé'
'राम मार्केटिंग प्राइवेट लिमिटेड' → 'राम मार्केटिंग प्राइवेट लिमिटेड'
'Lège-Cap-Ferret' → 'Lège-Cap-Ferret'
None → ''
'   2100   Cameron   Drive   ' → '2100 Cameron Drive'

# normalize_business_name()

In [91]:
%%writefile -a /kaggle/working/src/preprocess.py

def normalize_business_name(text):
    """
    Normalize business names for entity matching.

    Keeps Unicode characters intact while:
    - normalizing Unicode
    - converting to lowercase
    - expanding common business abbreviations
    - converting '&' to 'and'
    - removing punctuation
    - normalizing whitespace
    """

    text = normalize_unicode(text)

    if not text:
        return ""

    # Lowercase while preserving Unicode
    text = text.lower()

    # Normalize common business abbreviations
    replacements = {
        r"\bpvt\.?\b": "private",
        r"\bltd\.?\b": "limited",
        r"\bcorp\.?\b": "corporation",
    }

    for pattern, replacement in replacements.items():
        text = re.sub(pattern, replacement, text)

    # '&' → 'and'
    text = text.replace("&", " and ")

    # Remove punctuation while preserving Unicode letters,
    # numbers, and combining marks.
    cleaned = []

    for char in text:
        category = unicodedata.category(char)

        if category.startswith("P"):
            cleaned.append(" ")
        else:
            cleaned.append(char)

    text = "".join(cleaned)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

Appending to /kaggle/working/src/preprocess.py

# TEST C2

In [29]:
reload(preprocess)

tests = [
    "ABC Pvt. Ltd.",
    "XYZ Corp.",
    "R&D Pvt Ltd",
    "राम मार्केटिंग प्राइवेट लिमिटेड",
    "L'Oréal & Sons",
    "  ABC   PVT.   LTD.  "
]

for text in tests:
    print(repr(text), "→", repr(preprocess.normalize_business_name(text)))

'ABC Pvt. Ltd.' → 'abc private limited'
'XYZ Corp.' → 'xyz corporation'
'R&D Pvt Ltd' → 'r and d private limited'
'राम मार्केटिंग प्राइवेट लिमिटेड' → 'राम मार्केटिंग प्राइवेट लिमिटेड'
"L'Oréal & Sons" → 'l oréal and sons'
'  ABC   PVT.   LTD.  ' → 'abc private limited'

# normalize_business_address()

In [92]:
%%writefile -a /kaggle/working/src/preprocess.py

def normalize_business_address(text):
    """
    Normalize business addresses for entity matching.

    Keeps useful address information such as:
    - house numbers
    - street numbers
    - postal codes
    - Unicode characters

    Normalizes:
    - Unicode
    - lowercase
    - common address abbreviations
    - '&' to 'and'
    - punctuation
    - whitespace
    """

    text = normalize_unicode(text)

    if not text:
        return ""

    # Lowercase while preserving Unicode
    text = text.lower()

    # Common address abbreviations.
    # These are applied token-wise so that words containing
    # 'st' or 'rd' are not accidentally modified.
    replacements = {
        r"\bst\.?\b": "street",
        r"\brd\.?\b": "road",
    }

    for pattern, replacement in replacements.items():
        text = re.sub(pattern, replacement, text)

    # '&' → 'and'
    text = text.replace("&", " and ")

    # Remove punctuation while preserving Unicode letters,
    # numbers, and combining marks.
    cleaned = []

    for char in text:
        category = unicodedata.category(char)

        if category.startswith("P"):
            cleaned.append(" ")
        else:
            cleaned.append(char)

    text = "".join(cleaned)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

Appending to /kaggle/working/src/preprocess.py

# Test C3

In [31]:
reload(preprocess)

tests = [
    "2100 Cameron Drive",
    "797, Lake Town Block A",
    "H.NO 204 C ROAD",
    "914 PIERPOINT AVE",
    "13 Rue Fermat",
    "7 Rue Masséna",
    "  59 St. John's Rd.  ",
    None
]

for text in tests:
    print(repr(text), "→", repr(preprocess.normalize_business_address(text)))

'2100 Cameron Drive' → '2100 cameron drive'
'797, Lake Town Block A' → '797 lake town block a'
'H.NO 204 C ROAD' → 'h no 204 c road'
'914 PIERPOINT AVE' → '914 pierpoint ave'
'13 Rue Fermat' → '13 rue fermat'
'7 Rue Masséna' → '7 rue masséna'
"  59 St. John's Rd.  " → '59 street john s road'
None → ''

# extract_address_features()

In [94]:
%%writefile -a /kaggle/working/src/preprocess.py

def extract_address_features(text):
    """
    Extract country-agnostic numeric information from an address.

    Returns:
        A dictionary containing:
        - numbers: numeric sequences found in the address

    No country-specific postal-code assumptions are made.
    """

    text = normalize_unicode(text)

    if not text:
        return {
            "numbers": []
        }

    # Extract standalone numeric sequences.
    # Examples:
    # "2100 Cameron Drive" -> ["2100"]
    # "Unit 4 Building 12" -> ["4", "12"]
    numbers = re.findall(r"\d+", text)

    return {
        "numbers": numbers
    }

Appending to /kaggle/working/src/preprocess.py

# Test C4

In [33]:
reload(preprocess)

tests = [
    "2100 Cameron Drive",
    "797, Lake Town Block A",
    "H.NO 204 C ROAD",
    "13 Rue Fermat 75005",
    "Unit 4, Building 12",
    "No numbers here",
    None
]

for text in tests:
    print(repr(text), "→", preprocess.extract_address_features(text))

'2100 Cameron Drive' → {'numbers': ['2100']}
'797, Lake Town Block A' → {'numbers': ['797']}
'H.NO 204 C ROAD' → {'numbers': ['204']}
'13 Rue Fermat 75005' → {'numbers': ['13', '75005']}
'Unit 4, Building 12' → {'numbers': ['4', '12']}
'No numbers here' → {'numbers': []}
None → {'numbers': []}

# preprocess_dataframe()

In [95]:
%%writefile -a /kaggle/working/src/preprocess.py

import pandas as pd


def preprocess_dataframe(df):
    """
    Apply preprocessing to a source dataframe.

    Original columns are preserved.
    New columns:
        - business_name_clean
        - business_address_clean
        - address_numbers
    """

    df = df.copy()

    # Normalize business names
    df["business_name_clean"] = (
        df["business_name"]
        .apply(normalize_business_name)
    )

    # Normalize business addresses
    df["business_address_clean"] = (
        df["business_address"]
        .apply(normalize_business_address)
    )

    # Extract numeric address information
    df["address_numbers"] = (
        df["business_address"]
        .apply(lambda x: extract_address_features(x)["numbers"])
    )

    return df

Appending to /kaggle/working/src/preprocess.py

In [35]:
import pandas as pd

TRAIN_SOURCE1 = "/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source1.tsv"

train_source1 = pd.read_csv(
    TRAIN_SOURCE1,
    sep="\t"
)

print("Shape:", train_source1.shape)
print("Columns:", train_source1.columns.tolist())

train_source1.head()

Shape: (2206821, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

# Test Preprocessing

In [36]:
reload(preprocess)

sample = train_source1.head(5)

processed_sample = preprocess.preprocess_dataframe(sample)

processed_sample[
    [
        "entity_id",
        "business_name",
        "business_name_clean",
        "business_address",
        "business_address_clean",
        "address_numbers",
        "country"
    ]
]

,entity_id,business_name,business_name_clean,business_address,business_address_clean,address_numbers,country
0,S1-925783039,Orelee's Barbershop,orelee s barbershop,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,[1795],US
1,S1-773889195,Prime Money,prime money,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,[17560],US
2,S1-377745466,B+ Retail Inc,b+ retail inc,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,[1712],US
3,S1-133037285,Christ Chapel,christ chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,[2100],US
4,S1-755362802,Prabhav Business Center,prabhav business center,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,[797],India

# checking for precision

In [37]:
import pandas as pd

BASE = "/kaggle/input/datasets/lakshaygauniyal/amazon-ml-2026-dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/train"

s1 = pd.read_csv(f"{BASE}/train_source1.tsv", sep="\t")
s2 = pd.read_csv(f"{BASE}/train_source2.tsv", sep="\t")
s3 = pd.read_csv(f"{BASE}/train_source3.tsv", sep="\t")

train_all = pd.concat(
    [s1, s2, s3],
    ignore_index=True
)

print("S1:", s1.shape)
print("S2:", s2.shape)
print("S3:", s3.shape)
print("Combined:", train_all.shape)

S1: (2206821, 4)
S2: (5034616, 4)
S3: (5285603, 4)
Combined: (12527040, 4)

In [38]:
train_all.head()

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

In [39]:
from collections import Counter
import re

name_text = train_all["business_name"].fillna("").astype(str)

# Look at tokens that occur frequently in business names
name_tokens = Counter()

for text in name_text:
    tokens = re.findall(r"\b[\w]+\b", text, flags=re.UNICODE)
    name_tokens.update(token.lower() for token in tokens)

print("Total unique tokens:", len(name_tokens))
print("\nTop 100 business-name tokens:\n")

for token, count in name_tokens.most_common(100):
    print(f"{token:25} {count}")

Total unique tokens: 1457351

Top 100 business-name tokens:

limited                   1732219
private                   1609087
llc                       1463749
inc                       1064538
ltd                       980435
ट                         833711
pvt                       533724
र                         527505
ल                         477486
center                    455968
com                       414150
ड                         403737
l                         398047
म                         391138
प                         381698
स                         364678
partners                  355515
services                  347551
s                         344845
group                     328687
corp                      318933
co                        313730
and                       299187
india                     292427
c                         287292
इव                        246472
care                      239786
of                        227569
holdings                  208622
associates                194453
क                         193334
ட                         186175
llp                       182679
d                         155091
p                         147295
ట                         146608
ಟ                         139485
corporation               136146
health                    133832
service                   125383
a                         124945
enterprises               124822
ज                         124693
clinic                    122846
industries                120992
solutions                 114734
ventures                  111536
lp                        110983
trading                   110357
ট                         107745
m                         104813
global                    103986
pc                        103946
the                       100208
न                         97968
ग                         94845
ટ                         94765
brothers                  92700
technologies              87123
फ                         85737
ర                         84617
pediatric                 84294
public                    83383
medicine                  82906
य                         79304
international             79031
ರ                         78565
company                   77777
व                         76883
র                         75998
exports                   72614
foundation                71738
ர                         70836
pllc                      70751
റ                         70610
इ                         69322
ब                         68446
మ                         68298
డ                         68192
ల                         67648
dental                    67235
ಮ                         65670
trust                     64581
ಲ                         64284
ಡ                         64052
ર                         63751
ப                         62885
family                    62310
consultants               61340
స                         61139
ప                         60272
blue                      60227
ம                         58912
green                     58824
వ                         58670
ಪ                         56718
valley                    56575
capital                   56567
ল                         56212
summit                    56138

In [41]:
import pandas as pd
import re
from collections import Counter
from pathlib import Path


# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/kaggle/input/datasets/lakshaygauniyal/"
    "amazon-ml-2026-dataset/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource/dataset"
)

FILES = {
    "train_source1": BASE / "train/train_source1.tsv",
    "train_source2": BASE / "train/train_source2.tsv",
    "train_source3": BASE / "train/train_source3.tsv",
    "test_source1": BASE / "test/test_source1.tsv",
    "test_source2": BASE / "test/test_source2.tsv",
    "test_source3": BASE / "test/test_source3.tsv",
}


# ============================================================
# SETTINGS
# ============================================================

CHUNK_SIZE = 50_000

FAKE_NULLS = {
    "null",
    "none",
    "na",
    "n/a",
    "nan",
    "nil",
    "unknown"
}


# Indic Unicode ranges
INDIC_RANGES = [
    (0x0900, 0x097F),  # Devanagari
    (0x0980, 0x09FF),  # Bengali
    (0x0A00, 0x0A7F),  # Gurmukhi
    (0x0A80, 0x0AFF),  # Gujarati
    (0x0B00, 0x0B7F),  # Odia
    (0x0B80, 0x0BFF),  # Tamil
    (0x0C00, 0x0C7F),  # Telugu
    (0x0C80, 0x0CFF),  # Kannada
    (0x0D00, 0x0D7F),  # Malayalam
]


def contains_indic(text):
    if pd.isna(text):
        return False

    for char in str(text):
        code = ord(char)

        for start, end in INDIC_RANGES:
            if start <= code <= end:
                return True

    return False


def extract_words(text):
    """
    Unicode-aware word extraction.
    """
    return re.findall(
        r"\b[\wÀ-ÖØ-öø-ÿ]+\b",
        str(text).lower(),
        flags=re.UNICODE
    )


# ============================================================
# MAIN EDA FUNCTION
# ============================================================

def run_eda(filepath, source_name):

    print("\n" + "=" * 80)
    print(f"PROCESSING: {source_name}")
    print("=" * 80)

    # Counters
    france_name_words = Counter()
    france_address_words = Counter()

    address_two_letter_tokens = Counter()
    fake_null_counter = Counter()

    # Row statistics
    total_rows = 0

    country_total = Counter()
    country_missing_address = Counter()

    india_total = 0
    india_indic_rows = 0

    # --------------------------------------------------------
    # READ FILE IN CHUNKS
    # --------------------------------------------------------

    for chunk_number, chunk in enumerate(
        pd.read_csv(
            filepath,
            sep="\t",
            usecols=[
                "business_name",
                "business_address",
                "country"
            ],
            chunksize=CHUNK_SIZE
        ),
        start=1
    ):

        total_rows += len(chunk)

        # ----------------------------------------------------
        # COUNTRY
        # ----------------------------------------------------

        country_series = (
            chunk["country"]
            .fillna("")
            .astype(str)
            .str.strip()
            .str.lower()
        )

        # ----------------------------------------------------
        # MISSING ADDRESS
        # ----------------------------------------------------

        missing_address = chunk["business_address"].isna()

        for country, count in country_series.value_counts().items():

            country_total[country] += count

            country_missing_address[country] += (
                missing_address[country_series == country].sum()
            )

        # ----------------------------------------------------
        # INDIA + INDIC SCRIPT
        # ----------------------------------------------------

        india_mask = country_series == "india"

        india_rows = chunk[india_mask]

        india_total += len(india_rows)

        if len(india_rows) > 0:

            name_indic = india_rows["business_name"].apply(
                contains_indic
            )

            address_indic = india_rows["business_address"].apply(
                contains_indic
            )

            indic_any = name_indic | address_indic

            india_indic_rows += indic_any.sum()

        # ----------------------------------------------------
        # FRANCE VOCABULARY
        # ----------------------------------------------------

        france_mask = country_series == "france"

        france_rows = chunk[france_mask]

        for text in france_rows["business_name"].dropna():
            france_name_words.update(
                extract_words(text)
            )

        for text in france_rows["business_address"].dropna():
            france_address_words.update(
                extract_words(text)
            )

        # ----------------------------------------------------
        # ADDRESS ABBREVIATIONS + FAKE NULLS
        # ----------------------------------------------------

        for text in chunk["business_address"].dropna():

            text_lower = str(text).lower()

            # Two-letter alphabetic tokens
            two_letter_tokens = re.findall(
                r"\b[a-zA-Z]{2}\b",
                text_lower
            )

            address_two_letter_tokens.update(
                two_letter_tokens
            )

            # Fake null tokens
            tokens = re.findall(
                r"\b[\w/.-]+\b",
                text_lower
            )

            for token in tokens:

                if token in FAKE_NULLS:
                    fake_null_counter[token] += 1

        # ----------------------------------------------------
        # PROGRESS
        # ----------------------------------------------------

        if chunk_number % 5 == 0:
            print(
                f"Processed {total_rows:,} rows..."
            )

    # ========================================================
    # RESULTS
    # ========================================================

    print("\n" + "-" * 80)
    print("BASIC INFORMATION")
    print("-" * 80)

    print("Total rows:", f"{total_rows:,}")

    # --------------------------------------------------------
    # 1. FRANCE VOCABULARY
    # --------------------------------------------------------

    print("\n" + "-" * 80)
    print("1. FRANCE VOCABULARY — BUSINESS NAMES")
    print("-" * 80)

    print(
        france_name_words.most_common(30)
    )

    print("\n" + "-" * 80)
    print("1. FRANCE VOCABULARY — ADDRESSES")
    print("-" * 80)

    print(
        france_address_words.most_common(30)
    )

    # --------------------------------------------------------
    # 2. ADDRESS ABBREVIATIONS
    # --------------------------------------------------------

    print("\n" + "-" * 80)
    print("2. COMMON TWO-LETTER ADDRESS TOKENS")
    print("-" * 80)

    print(
        address_two_letter_tokens.most_common(50)
    )

    # --------------------------------------------------------
    # 2B. FAKE NULLS
    # --------------------------------------------------------

    print("\n" + "-" * 80)
    print("2B. FAKE NULL WORDS IN ADDRESSES")
    print("-" * 80)

    print(
        dict(fake_null_counter)
    )

    # --------------------------------------------------------
    # 3. INDIC SCRIPT
    # --------------------------------------------------------

    print("\n" + "-" * 80)
    print("3. INDIC SCRIPT — INDIA")
    print("-" * 80)

    indic_percentage = (
        india_indic_rows / india_total * 100
        if india_total > 0
        else 0
    )

    print(
        f"Indic rows: {india_indic_rows:,} / "
        f"{india_total:,}"
    )

    print(
        f"Percentage: {indic_percentage:.2f}%"
    )

    # --------------------------------------------------------
    # 4. MISSING ADDRESS
    # --------------------------------------------------------

    print("\n" + "-" * 80)
    print("4. MISSING ADDRESS BY COUNTRY")
    print("-" * 80)

    for country in ["us", "india", "france"]:

        total = country_total[country]
        missing = country_missing_address[country]

        percentage = (
            missing / total * 100
            if total > 0
            else 0
        )

        print(
            f"{country.upper():8} "
            f"{missing:,} / {total:,} "
            f"= {percentage:.2f}%"
        )

    # Return results as a dictionary too
    return {
        "total_rows": total_rows,
        "france_name_top30": france_name_words.most_common(30),
        "france_address_top30": france_address_words.most_common(30),
        "two_letter_address_tokens": address_two_letter_tokens.most_common(50),
        "fake_nulls": dict(fake_null_counter),
        "india_total": india_total,
        "india_indic_rows": india_indic_rows,
        "india_indic_percentage": indic_percentage,
        "country_total": dict(country_total),
        "country_missing_address": dict(country_missing_address)
    }

# >  Learn abbreavations from the ground truth set

# Load and inspect the ground truth

In [1]:
import pandas as pd

GROUND_TRUTH = (
    "/kaggle/input/datasets/lakshaygauniyal/"
    "amazon-ml-2026-dataset/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource/dataset/train/"
    "train_ground_truth.tsv"
)

gt = pd.read_csv(
    GROUND_TRUTH,
    sep="\t"
)

print("Shape:", gt.shape)
print("\nColumns:")
print(gt.columns.tolist())

display(gt.head(10))

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
Shape: (2206821, 2)

Columns:
['source1_entity_id', 'matched_entity_ids']

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [2]:
# ============================================================
# EXTRACT REQUIRED ENTITY IDs
# ============================================================

# Every S1 ID appearing in ground truth
s1_ids = set(
    gt["source1_entity_id"]
    .dropna()
    .astype(str)
)

# S2 and S3 IDs appearing inside matched_entity_ids
s2_ids = set()
s3_ids = set()

for value in gt["matched_entity_ids"].dropna().astype(str):

    for entity_id in value.split(","):

        entity_id = entity_id.strip()

        if entity_id.startswith("S2-"):
            s2_ids.add(entity_id)

        elif entity_id.startswith("S3-"):
            s3_ids.add(entity_id)

print("\nRequired IDs")
print("-" * 30)
print("S1:", len(s1_ids))
print("S2:", len(s2_ids))
print("S3:", len(s3_ids))

print("\nExample S1 IDs:", list(s1_ids)[:5])
print("Example S2 IDs:", list(s2_ids)[:5])
print("Example S3 IDs:", list(s3_ids)[:5])

Required IDs
------------------------------
S1: 2206821
S2: 3693619
S3: 3944746

Example S1 IDs: ['S1-150915814', 'S1-488657287', 'S1-452726137', 'S1-392613239', 'S1-654207966']
Example S2 IDs: ['S2-457506318', 'S2-751569554', 'S2-344992073', 'S2-148469740', 'S2-321230444']
Example S3 IDs: ['S3-164941887', 'S3-626448832', 'S3-144024958', 'S3-291977543', 'S3-491321233']

In [3]:
import duckdb

print("DuckDB version:", duckdb.__version__)

DuckDB version: 1.3.2

In [5]:
# ============================================================
# DATASET PATHS
# ============================================================

BASE = (
    "/kaggle/input/datasets/lakshaygauniyal/"
    "amazon-ml-2026-dataset/"
    "6ab10eb3b23ba_student_resource/"
    "student_resource/dataset"
)

SOURCE1 = f"{BASE}/train/train_source1.tsv"
SOURCE2 = f"{BASE}/train/train_source2.tsv"
SOURCE3 = f"{BASE}/train/train_source3.tsv"

GROUND_TRUTH = f"{BASE}/train/train_ground_truth.tsv"


# ============================================================
# DUCKDB
# ============================================================

con = duckdb.connect()

print("DuckDB version:", duckdb.__version__)


# ============================================================
# CHECK SCHEMA
# ============================================================

for name, path in {
    "S1": SOURCE1,
    "S2": SOURCE2,
    "S3": SOURCE3,
}.items():

    print(f"\n{name} schema")
    print("=" * 50)

    schema = con.execute(f"""
        DESCRIBE
        SELECT *
        FROM read_csv_auto(
            '{path}',
            delim='\\t'
        )
    """).fetchdf()

    display(schema)


# ============================================================
# SAMPLE
# ============================================================

print("\nS1 sample")
print("=" * 50)

sample = con.execute(f"""
    SELECT *
    FROM read_csv_auto(
        '{SOURCE1}',
        delim='\\t'
    )
    LIMIT 5
""").fetchdf()

display(sample)

DuckDB version: 1.3.2

S1 schema
==================================================

        column_name column_type null   key default extra
0         entity_id     VARCHAR  YES  None    None  None
1     business_name     VARCHAR  YES  None    None  None
2  business_address     VARCHAR  YES  None    None  None
3           country     VARCHAR  YES  None    None  None

S2 schema
==================================================

        column_name column_type null   key default extra
0         entity_id     VARCHAR  YES  None    None  None
1     business_name     VARCHAR  YES  None    None  None
2  business_address     VARCHAR  YES  None    None  None
3           country     VARCHAR  YES  None    None  None

S3 schema
==================================================

        column_name column_type null   key default extra
0         entity_id     VARCHAR  YES  None    None  None
1     business_name     VARCHAR  YES  None    None  None
2  business_address     VARCHAR  YES  None    None  None
3           country     VARCHAR  YES  None    None  None

S1 sample
==================================================

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

In [6]:
# ============================================================
# BUILD S1 -> MATCHED S2/S3 PAIRS
# ============================================================

pairs = con.execute(f"""
    WITH gt AS (
        SELECT
            source1_entity_id AS s1_id,
            UNNEST(
                STRING_SPLIT(matched_entity_ids, ',')
            ) AS matched_id
        FROM read_csv_auto(
            '{GROUND_TRUTH}',
            delim='\\t'
        )
        WHERE matched_entity_ids IS NOT NULL
    )

    SELECT
        s1_id,
        TRIM(matched_id) AS matched_id,
        CASE
            WHEN TRIM(matched_id) LIKE 'S2-%' THEN 'S2'
            WHEN TRIM(matched_id) LIKE 'S3-%' THEN 'S3'
            ELSE 'UNKNOWN'
        END AS source
    FROM gt
    WHERE
        TRIM(matched_id) LIKE 'S2-%'
        OR TRIM(matched_id) LIKE 'S3-%'
""").fetchdf()

print("Total matched pairs:", len(pairs))

print("\nPairs by source:")
print(pairs["source"].value_counts())

display(pairs.head(20))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Total matched pairs: 7638365

Pairs by source:
source
S3    3944746
S2    3693619
Name: count, dtype: int64

           s1_id    matched_id source
0      S1-965667  S2-681193310     S2
1      S1-965667  S2-743505751     S2
2      S1-965667  S3-775321672     S3
3      S1-965667   S3-11291185     S3
4      S1-965667  S3-860443364     S3
5    S1-55344266  S2-249013014     S2
6    S1-55344266  S2-197070651     S2
7    S1-55344266  S3-478195123     S3
8    S1-55344266  S3-384364074     S3
9   S1-343815751  S2-790675320     S2
10  S1-343815751  S2-479876582     S2
11  S1-343815751  S3-878454467     S3
12  S1-656753428  S2-153058913     S2
13  S1-656753428   S2-24659151     S2
14  S1-656753428  S3-679606215     S3
15  S1-102811957  S2-478959098     S2
16  S1-102811957  S2-553508714     S2
17  S1-102811957  S2-625774905     S2
18  S1-102811957  S3-728090388     S3
19  S1-102811957  S3-928796641     S3

In [7]:
# ============================================================
# CREATE MATCHED RECORDS INSIDE DUCKDB
# ============================================================

con.execute("DROP TABLE IF EXISTS matched_records")

query = f"""
CREATE TEMP TABLE matched_records AS

-- ==========================================================
-- S1 <-> S2
-- ==========================================================

SELECT
    gt.source1_entity_id AS s1_id,

    s1.business_name    AS s1_name,
    s1.business_address AS s1_address,

    TRIM(matched_id)    AS matched_id,
    'S2'                AS matched_source,

    s2.business_name    AS matched_name,
    s2.business_address AS matched_address

FROM read_csv_auto(
    '{GROUND_TRUTH}',
    delim='\\t'
) gt

JOIN read_csv_auto(
    '{SOURCE1}',
    delim='\\t'
) s1
    ON s1.entity_id = gt.source1_entity_id

CROSS JOIN UNNEST(
    STRING_SPLIT(gt.matched_entity_ids, ',')
) AS u(matched_id)

JOIN read_csv_auto(
    '{SOURCE2}',
    delim='\\t'
) s2
    ON s2.entity_id = TRIM(matched_id)

WHERE TRIM(matched_id) LIKE 'S2-%'


UNION ALL


-- ==========================================================
-- S1 <-> S3
-- ==========================================================

SELECT
    gt.source1_entity_id AS s1_id,

    s1.business_name    AS s1_name,
    s1.business_address AS s1_address,

    TRIM(matched_id)    AS matched_id,
    'S3'                AS matched_source,

    s3.business_name    AS matched_name,
    s3.business_address AS matched_address

FROM read_csv_auto(
    '{GROUND_TRUTH}',
    delim='\\t'
) gt

JOIN read_csv_auto(
    '{SOURCE1}',
    delim='\\t'
) s1
    ON s1.entity_id = gt.source1_entity_id

CROSS JOIN UNNEST(
    STRING_SPLIT(gt.matched_entity_ids, ',')
) AS u(matched_id)

JOIN read_csv_auto(
    '{SOURCE3}',
    delim='\\t'
) s3
    ON s3.entity_id = TRIM(matched_id)

WHERE TRIM(matched_id) LIKE 'S3-%'
"""

print("Building matched_records...")
con.execute(query)

print("Done.")

Building matched_records...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Done.

In [8]:
print(
    con.execute("""
        SELECT COUNT(*) AS total
        FROM matched_records
    """).fetchdf()
)

display(
    con.execute("""
        SELECT *
        FROM matched_records
        LIMIT 10
    """).fetchdf()
)

     total
0  7638365

,s1_id,s1_name,s1_address,matched_id,matched_source,matched_name,matched_address
0,S1-479800260,Olivo Colonial Railway Inc,"110 Gregory Court, Grandy, NC",S2-349130645,S2,Olivo Colonial,"GREGORY CT, GRANDYTOWNSHIP, NC"
1,S1-963257029,Pacific Quality Westin Inc.,"208 Copia Street, City Of El Paso, TX",S2-859271394,S2,Pacific Qúality Westin,"208 1/2 COPIA ST, CITY OF EL PASO, TX"
2,S1-306947266,Kunda Biscuits Public Limited,"#372, 2Nd Floor, 100Ft Road, Sk Karim Khan Roa...",S2-532735457,S2,M/s kundabiscuitspublic.com,"NO #372 , 2ND FLOOR, 100FT ROAD, SK KARIM KHAN..."
3,S1-793133616,Kannan Polyfoam,"Wework Galaxy43 Residency, Road Shanthala Naga...",S2-943521130,S2,KANNAN POLYFOAM-LTD,"WEWORK GALAXY43 RESIDENCY, ROAD SHANTHALA NAGA..."
4,S1-143060045,Sasonor Family Office Inc,"1315 Spring Cove Road, Sunrise Beach, MO",S2-61217893,S2,Sasonor Family Office Inc,"1315 SPRING COVE RD, SUNRISEBEACH, MO"
5,S1-441967577,Physical Therapy Medicine of Ramapo LLC,"32 Blauvelt Road, Unit Unit 201, Ramapo, NY",S2-692100125,S2,Physical Therapy Medicine of Ramapo L.L.C.,"BLAUVELT ROAD, MONSEY, NY"
6,S1-427038025,Tion PC,"Fayetteville, 1103 Madonna Drive, NC",S2-438740741,S2,TION,"1103 MADONNA DR, FAYETTEVILLE TOWNSHIP, NC"
7,S1-701829417,"Zitecex, LLC","7361 New Britain Drive, Memphis, TN",S2-348203587,S2,Mirakeloumbra,"7361 NEW BRITAIN DR, MEMPHIS, TN"
8,S1-392122905,Loa Value Eastern Inc.,"437 Palisade Avenue, Unit Apartment K5, Yonker...",S2-506439470,S2,Loa Value Eastern Inc,None
9,S1-256290593,Rajpur Mercantile Ltd,"184, Guru Kripa Colony, Rajpur, Barwani, Madhy...",S2-980510855,S2,Rajpur Mercantile Ltd.,"184, GURU KRIPA COLONY, RAJPUR, Madhya Pradesh"

In [9]:
# ============================================================
# STEP 5A
# DISCOVER FREQUENT TOKEN DIFFERENCES
# ============================================================

import re
from collections import Counter


def tokenize(text):
    if text is None:
        return []

    text = str(text).lower()

    # Keep Unicode letters/numbers
    tokens = re.findall(r"[^\W_]+", text, flags=re.UNICODE)

    return tokens


# Take a manageable sample first
sample_pairs = con.execute("""
    SELECT
        s1_name,
        matched_name,
        s1_address,
        matched_address,
        matched_source
    FROM matched_records
    USING SAMPLE 100000 ROWS
""").fetchdf()

print("Sample size:", len(sample_pairs))


# ------------------------------------------------------------
# Collect token differences
# ------------------------------------------------------------

name_additions = Counter()
name_removals = Counter()

address_additions = Counter()
address_removals = Counter()


for row in sample_pairs.itertuples(index=False):

    # -------------------------
    # BUSINESS NAME
    # -------------------------

    s1_tokens = set(tokenize(row.s1_name))
    matched_tokens = set(tokenize(row.matched_name))

    additions = matched_tokens - s1_tokens
    removals = s1_tokens - matched_tokens

    for token in additions:
        name_additions[token] += 1

    for token in removals:
        name_removals[token] += 1


    # -------------------------
    # ADDRESS
    # -------------------------

    s1_tokens = set(tokenize(row.s1_address))
    matched_tokens = set(tokenize(row.matched_address))

    additions = matched_tokens - s1_tokens
    removals = s1_tokens - matched_tokens

    for token in additions:
        address_additions[token] += 1

    for token in removals:
        address_removals[token] += 1


print("\nTop name additions:")
print(name_additions.most_common(30))

print("\nTop name removals:")
print(name_removals.most_common(30))

print("\nTop address additions:")
print(address_additions.most_common(30))

print("\nTop address removals:")
print(address_removals.most_common(30))

Sample size: 100000

Top name additions:
[('com', 5217), ('ल', 4042), ('ट', 3915), ('र', 3873), ('प', 3597), ('ड', 3533), ('म', 3490), ('ltd', 3436), ('center', 2929), ('इव', 2756), ('स', 2618), ('services', 2087), ('क', 1716), ('inc', 1454), ('l', 1199), ('ज', 1104), ('service', 1016), ('c', 987), ('llc', 986), ('co', 961), ('न', 938), ('ग', 908), ('फ', 885), ('corporation', 874), ('corp', 868), ('partners', 814), ('the', 803), ('य', 762), ('व', 719), ('इ', 672)]

Top name removals:
[('limited', 13897), ('private', 8525), ('llc', 5862), ('inc', 4299), ('ltd', 3195), ('pvt', 1726), ('c', 980), ('llp', 976), ('care', 709), ('group', 693), ('corp', 657), ('india', 598), ('associates', 570), ('pc', 542), ('and', 529), ('co', 514), ('p', 505), ('partners', 505), ('services', 505), ('l', 496), ('solutions', 473), ('center', 466), ('global', 445), ('international', 441), ('pllc', 434), ('technologies', 416), ('trading', 402), ('clinic', 382), ('industries', 378), ('foundation', 374)]

Top address additions:
[('st', 5793), ('rd', 5618), ('dr', 5160), ('ave', 4174), ('no', 2895), ('र', 2658), ('null', 2428), ('ln', 2174), ('ष', 2094), ('ट', 2094), ('मह', 2094), ('door', 1784), ('h', 1693), ('city', 1645), ('mh', 1580), ('a', 1549), ('texas', 1478), ('1', 1452), ('new', 1380), ('2', 1336), ('ct', 1304), ('north', 1290), ('द', 1230), ('ल', 1230), ('york', 1195), ('carolina', 1137), ('dl', 1030), ('रद', 1008), ('प', 1008), ('श', 1008)]

Top address removals:
[('road', 8162), ('street', 7344), ('unit', 7299), ('drive', 5757), ('avenue', 4703), ('maharashtra', 4049), ('lane', 2519), ('west', 2427), ('pradesh', 2396), ('no', 2256), ('city', 2224), ('tx', 1778), ('nagar', 1687), ('uttar', 1492), ('court', 1482), ('karnataka', 1477), ('floor', 1466), ('ny', 1431), ('tamil', 1402), ('nadu', 1401), ('telangana', 1401), ('1', 1372), ('nc', 1319), ('bengal', 1223), ('plot', 1175), ('gujarat', 1157), ('oh', 1107), ('south', 1070), ('il', 1049), ('fl', 966)]

In [10]:
import re
import unicodedata
from collections import Counter


# ============================================================
# TOKENIZATION FOR ABBREVIATION DISCOVERY
# ============================================================

def comparison_tokens(text):
    """
    Normalize only for discovering token substitutions.

    IMPORTANT:
    This is NOT our final preprocessing normalization.
    """

    if text is None:
        return []

    text = str(text)

    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)

    # Lowercase
    text = text.lower()

    # Remove punctuation WITHOUT converting it to spaces.
    # Example:
    #   L.L.C. -> llc
    #   St.     -> st
    text = "".join(
        char
        for char in text
        if not unicodedata.category(char).startswith("P")
    )

    # Unicode-aware tokenization
    return re.findall(r"[^\W_]+", text, flags=re.UNICODE)


# ============================================================
# DISCOVER ONE-TOKEN SUBSTITUTIONS
# ============================================================

name_changes = Counter()
address_changes = Counter()


for row in sample_pairs.itertuples(index=False):

    # --------------------------------------------------------
    # BUSINESS NAME
    # --------------------------------------------------------

    a = comparison_tokens(row.s1_name)
    b = comparison_tokens(row.matched_name)

    if len(a) == len(b):

        differences = [
            (x, y)
            for x, y in zip(a, b)
            if x != y
        ]

        # EXACTLY ONE token changed
        if len(differences) == 1:

            old_token, new_token = differences[0]

            name_changes[(old_token, new_token)] += 1


    # --------------------------------------------------------
    # ADDRESS
    # --------------------------------------------------------

    a = comparison_tokens(row.s1_address)
    b = comparison_tokens(row.matched_address)

    if len(a) == len(b):

        differences = [
            (x, y)
            for x, y in zip(a, b)
            if x != y
        ]

        # EXACTLY ONE token changed
        if len(differences) == 1:

            old_token, new_token = differences[0]

            address_changes[(old_token, new_token)] += 1


# ============================================================
# DISPLAY RESULTS
# ============================================================

print("NAME TOKEN SUBSTITUTIONS")
print("=" * 60)

for (old, new), count in name_changes.most_common(50):
    print(f"{old:25} -> {new:25} : {count}")


print("\nADDRESS TOKEN SUBSTITUTIONS")
print("=" * 60)

for (old, new), count in address_changes.most_common(50):
    print(f"{old:25} -> {new:25} : {count}")

NAME TOKEN SUBSTITUTIONS
============================================================
limited                   -> ltd                       : 1764
inc                       -> incorporated              : 439
ltd                       -> limited                   : 268
inc                       -> ínc                       : 196
limited                   -> límited                   : 193
private                   -> prívate                   : 157
pc                        -> inc                       : 102
pc                        -> llc                       : 93
corp                      -> corporation               : 77
company                   -> co                        : 65
co                        -> company                   : 56
center                    -> cénter                    : 48
group                     -> llc                       : 46
group                     -> inc                       : 45
group                     -> gróup                     : 44
care                      -> cáre                      : 42
and                       -> ánd                       : 42
corporation               -> corp                      : 42
india                     -> índia                     : 38
co                        -> có                        : 35
lp                        -> llc                       : 34
associates                -> ássociates                : 34
corp                      -> córp                      : 29
partners                  -> pártners                  : 29
of                        -> óf                        : 25
services                  -> sérvices                  : 24
lp                        -> inc                       : 21
clinic                    -> clínic                    : 21
trust                     -> trúst                     : 20
international             -> ínternational             : 19
center                    -> centre                    : 17
inc                       -> lnc                       : 17
solutions                 -> sólutions                 : 17
india                     -> lndia                     : 17
trading                   -> tráding                   : 17
medicine                  -> médicine                  : 17
limited                   -> private                   : 16
health                    -> héalth                    : 15
brothers                  -> bróthers                  : 15
industries                -> índustries                : 15
fund                      -> fúnd                      : 13
industries                -> lndustries                : 13
association               -> ássociation               : 13
global                    -> glóbal                    : 13
specialists               -> spécialists               : 13
physicians                -> physícians                : 13
foundation                -> fóundation                : 13
corporation               -> córporation               : 13
institute                 -> ínstitute                 : 13
ventures                  -> véntures                  : 13

ADDRESS TOKEN SUBSTITUTIONS
============================================================
road                      -> rd                        : 1153
drive                     -> dr                        : 1073
street                    -> st                        : 1017
avenue                    -> ave                       : 806
lane                      -> ln                        : 485
tx                        -> texas                     : 280
court                     -> ct                        : 259
maharashtra               -> mh                        : 227
delhi                     -> dl                        : 157
oh                        -> ohio                      : 152
il                        -> illinois                  : 140
circle                    -> cir                       : 125
place                     -> pl                        : 113
street                    -> saint                     : 107
tn                        -> tennessee                 : 103
ma                        -> massachusetts             : 102
gujarat                   -> gj                        : 90
in                        -> indiana                   : 86
karnataka                 -> ka                        : 85
boulevard                 -> blvd                      : 70
az                        -> arizona                   : 66
ca                        -> california                : 65
al                        -> alabama                   : 65
va                        -> virginia                  : 63
ky                        -> kentucky                  : 62
mn                        -> minnesota                 : 56
trail                     -> trl                       : 56
md                        -> maryland                  : 55
kerala                    -> keralam                   : 55
rajasthan                 -> rj                        : 53
ut                        -> utah                      : 53
wa                        -> washington                : 52
ar                        -> arkansas                  : 50
haryana                   -> hr                        : 50
wi                        -> wisconsin                 : 50
or                        -> oregon                    : 48
telangana                 -> tg                        : 45
ia                        -> iowa                      : 41
mo                        -> missouri                  : 40
ok                        -> oklahoma                  : 39
bihar                     -> br                        : 39
kerala                    -> kl                        : 34
ct                        -> connecticut               : 33
orissa                    -> odisha                    : 33
highway                   -> hwy                       : 27
terrace                   -> ter                       : 24
parkway                   -> pkwy                      : 23
orissa                    -> od                        : 21
punjab                    -> pb                        : 19
mt                        -> montana                   : 18

# Confidence calculation

In [11]:
from collections import defaultdict, Counter

# ============================================================
# BUILD TOKEN TRANSITION COUNTS
#
# For every comparable pair where ONLY ONE TOKEN differs:
#
#       old_token -> new_token
#
# Also count unchanged tokens:
#
#       old_token -> same_token
# ============================================================


def collect_token_statistics(rows, text_col_1, text_col_2):

    transitions = defaultdict(Counter)

    for row in rows.itertuples(index=False):

        a = comparison_tokens(getattr(row, text_col_1))
        b = comparison_tokens(getattr(row, text_col_2))

        # Only compare records with the same number of tokens
        if len(a) != len(b):
            continue

        differences = [
            (x, y)
            for x, y in zip(a, b)
            if x != y
        ]

        # We only want ONE-token differences
        if len(differences) != 1:
            continue

        old_token, new_token = differences[0]

        transitions[old_token][new_token] += 1

    return transitions


# ============================================================
# NAME
# ============================================================

name_transitions = collect_token_statistics(
    sample_pairs,
    "s1_name",
    "matched_name"
)


# ============================================================
# ADDRESS
# ============================================================

address_transitions = collect_token_statistics(
    sample_pairs,
    "s1_address",
    "matched_address"
)


# ============================================================
# SHOW CANDIDATES WITH CONFIDENCE
# ============================================================

def show_candidates(transitions, min_count=20):

    candidates = []

    for old_token, counter in transitions.items():

        total = sum(counter.values())

        new_token, count = counter.most_common(1)[0]

        confidence = count / total

        candidates.append(
            (
                old_token,
                new_token,
                count,
                total,
                confidence
            )
        )

    candidates.sort(
        key=lambda x: (x[4], x[2]),
        reverse=True
    )

    for old, new, count, total, confidence in candidates:

        if count >= min_count:

            print(
                f"{old:20} -> "
                f"{new:20} | "
                f"count={count:5} | "
                f"total={total:5} | "
                f"confidence={confidence:.3f}"
            )


print("=" * 80)
print("BUSINESS NAME CANDIDATES")
print("=" * 80)

show_candidates(name_transitions)


print("\n" + "=" * 80)
print("ADDRESS CANDIDATES")
print("=" * 80)

show_candidates(address_transitions)

================================================================================
BUSINESS NAME CANDIDATES
================================================================================
and                  -> ánd                  | count=   42 | total=   45 | confidence=0.933
ltd                  -> limited              | count=  268 | total=  288 | confidence=0.931
limited              -> ltd                  | count= 1764 | total= 2012 | confidence=0.877
of                   -> óf                   | count=   25 | total=   29 | confidence=0.862
company              -> co                   | count=   65 | total=   82 | confidence=0.793
corp                 -> corporation          | count=   77 | total=  109 | confidence=0.706
corporation          -> corp                 | count=   42 | total=   64 | confidence=0.656
inc                  -> incorporated         | count=  439 | total=  715 | confidence=0.614
lp                   -> llc                  | count=   34 | total=   58 | confidence=0.586
co                   -> company              | count=   56 | total=  108 | confidence=0.519
pc                   -> inc                  | count=  102 | total=  202 | confidence=0.505
center               -> cénter               | count=   48 | total=  159 | confidence=0.302
group                -> llc                  | count=   46 | total=  171 | confidence=0.269
care                 -> cáre                 | count=   42 | total=  159 | confidence=0.264
trust                -> trúst                | count=   20 | total=   78 | confidence=0.256
associates           -> ássociates           | count=   34 | total=  141 | confidence=0.241
services             -> sérvices             | count=   24 | total=  101 | confidence=0.238
private              -> prívate              | count=  157 | total=  676 | confidence=0.232
india                -> índia                | count=   38 | total=  166 | confidence=0.229
partners             -> pártners             | count=   29 | total=  147 | confidence=0.197
clinic               -> clínic               | count=   21 | total=  108 | confidence=0.194

================================================================================
ADDRESS CANDIDATES
================================================================================
tx                   -> texas                | count=  280 | total=  280 | confidence=1.000
maharashtra          -> mh                   | count=  227 | total=  227 | confidence=1.000
oh                   -> ohio                 | count=  152 | total=  152 | confidence=1.000
il                   -> illinois             | count=  140 | total=  140 | confidence=1.000
tn                   -> tennessee            | count=  103 | total=  103 | confidence=1.000
ma                   -> massachusetts        | count=  102 | total=  102 | confidence=1.000
gujarat              -> gj                   | count=   90 | total=   90 | confidence=1.000
in                   -> indiana              | count=   86 | total=   86 | confidence=1.000
az                   -> arizona              | count=   66 | total=   66 | confidence=1.000
ca                   -> california           | count=   65 | total=   65 | confidence=1.000
al                   -> alabama              | count=   65 | total=   65 | confidence=1.000
va                   -> virginia             | count=   63 | total=   63 | confidence=1.000
ky                   -> kentucky             | count=   62 | total=   62 | confidence=1.000
mn                   -> minnesota            | count=   56 | total=   56 | confidence=1.000
md                   -> maryland             | count=   55 | total=   55 | confidence=1.000
rajasthan            -> rj                   | count=   53 | total=   53 | confidence=1.000
ut                   -> utah                 | count=   53 | total=   53 | confidence=1.000
wa                   -> washington           | count=   52 | total=   52 | confidence=1.000
ar                   -> arkansas             | count=   50 | total=   50 | confidence=1.000
haryana              -> hr                   | count=   50 | total=   50 | confidence=1.000
wi                   -> wisconsin            | count=   50 | total=   50 | confidence=1.000
or                   -> oregon               | count=   48 | total=   48 | confidence=1.000
telangana            -> tg                   | count=   45 | total=   45 | confidence=1.000
ia                   -> iowa                 | count=   41 | total=   41 | confidence=1.000
mo                   -> missouri             | count=   40 | total=   40 | confidence=1.000
ok                   -> oklahoma             | count=   39 | total=   39 | confidence=1.000
bihar                -> br                   | count=   39 | total=   39 | confidence=1.000
ct                   -> connecticut          | count=   33 | total=   33 | confidence=1.000
terrace              -> ter                  | count=   24 | total=   24 | confidence=1.000
parkway              -> pkwy                 | count=   23 | total=   23 | confidence=1.000
karnataka            -> ka                   | count=   85 | total=   86 | confidence=0.988
lane                 -> ln                   | count=  485 | total=  491 | confidence=0.988
court                -> ct                   | count=  259 | total=  263 | confidence=0.985
trail                -> trl                  | count=   56 | total=   57 | confidence=0.982
drive                -> dr                   | count= 1073 | total= 1096 | confidence=0.979
circle               -> cir                  | count=  125 | total=  128 | confidence=0.977
road                 -> rd                   | count= 1153 | total= 1182 | confidence=0.975
place                -> pl                   | count=  113 | total=  116 | confidence=0.974
delhi                -> dl                   | count=  157 | total=  162 | confidence=0.969
avenue               -> ave                  | count=  806 | total=  832 | confidence=0.969
boulevard            -> blvd                 | count=   70 | total=   77 | confidence=0.909
street               -> st                   | count= 1017 | total= 1150 | confidence=0.884
highway              -> hwy                  | count=   27 | total=   33 | confidence=0.818
kerala               -> keralam              | count=   55 | total=   89 | confidence=0.618
orissa               -> odisha               | count=   33 | total=   54 | confidence=0.611

In [14]:
# ============================================================
# FILTER ADDRESS CANDIDATES
# Separate likely state mappings from actual abbreviations
# ============================================================

US_STATES = {
    "alabama", "alaska", "arizona", "arkansas", "california",
    "colorado", "connecticut", "delaware", "florida", "georgia",
    "hawaii", "idaho", "illinois", "indiana", "iowa",
    "kansas", "kentucky", "louisiana", "maine", "maryland",
    "massachusetts", "michigan", "minnesota", "mississippi",
    "missouri", "montana", "nebraska", "nevada",
    "new hampshire", "new jersey", "new mexico", "new york",
    "north carolina", "north dakota", "ohio", "oklahoma", "oregon",
    "pennsylvania", "rhode island", "south carolina", "south dakota",
    "tennessee", "texas", "utah", "vermont", "virginia",
    "washington", "west virginia", "wisconsin", "wyoming"
}

INDIA_STATES = {
    "andhra pradesh", "arunachal pradesh", "assam", "bihar",
    "chhattisgarh", "goa", "gujarat", "haryana", "himachal pradesh",
    "jharkhand", "karnataka", "kerala", "madhya pradesh",
    "maharashtra", "manipur", "meghalaya", "mizoram", "nagaland",
    "odisha", "punjab", "rajasthan", "sikkim", "tamil nadu",
    "telangana", "tripura", "uttar pradesh", "uttarakhand",
    "west bengal","delhi"
}

STATE_NAMES = US_STATES | INDIA_STATES


# ------------------------------------------------------------
# Separate address transformations
# ------------------------------------------------------------

state_candidates = []
abbreviation_candidates = []

for old_token, counter in address_transitions.items():

    total = sum(counter.values())

    new_token, count = counter.most_common(1)[0]

    confidence = count / total

    if count < 20:
        continue

    candidate = (
        old_token,
        new_token,
        count,
        total,
        confidence
    )

    # If either side is a state name, classify separately
    if (
        old_token in STATE_NAMES
        or new_token in STATE_NAMES
    ):
        state_candidates.append(candidate)
    else:
        abbreviation_candidates.append(candidate)


# Sort
state_candidates.sort(key=lambda x: (x[4], x[2]), reverse=True)
abbreviation_candidates.sort(key=lambda x: (x[4], x[2]), reverse=True)


# ============================================================
# STATE MAPPINGS
# ============================================================

print("=" * 90)
print("STATE / GEOGRAPHIC MAPPINGS")
print("=" * 90)

for old, new, count, total, confidence in state_candidates[:50]:

    print(
        f"{old:20} -> "
        f"{new:20} | "
        f"count={count:5} | "
        f"total={total:5} | "
        f"confidence={confidence:.3f}"
    )


# ============================================================
# ACTUAL ADDRESS ABBREVIATION CANDIDATES
# ============================================================

print("\n" + "=" * 90)
print("NON-GEOGRAPHIC ADDRESS CANDIDATES")
print("=" * 90)

for old, new, count, total, confidence in abbreviation_candidates[:50]:

    print(
        f"{old:20} -> "
        f"{new:20} | "
        f"count={count:5} | "
        f"total={total:5} | "
        f"confidence={confidence:.3f}"
    )

==========================================================================================
STATE / GEOGRAPHIC MAPPINGS
==========================================================================================
tx                   -> texas                | count=  280 | total=  280 | confidence=1.000
maharashtra          -> mh                   | count=  227 | total=  227 | confidence=1.000
oh                   -> ohio                 | count=  152 | total=  152 | confidence=1.000
il                   -> illinois             | count=  140 | total=  140 | confidence=1.000
tn                   -> tennessee            | count=  103 | total=  103 | confidence=1.000
ma                   -> massachusetts        | count=  102 | total=  102 | confidence=1.000
gujarat              -> gj                   | count=   90 | total=   90 | confidence=1.000
in                   -> indiana              | count=   86 | total=   86 | confidence=1.000
az                   -> arizona              | count=   66 | total=   66 | confidence=1.000
ca                   -> california           | count=   65 | total=   65 | confidence=1.000
al                   -> alabama              | count=   65 | total=   65 | confidence=1.000
va                   -> virginia             | count=   63 | total=   63 | confidence=1.000
ky                   -> kentucky             | count=   62 | total=   62 | confidence=1.000
mn                   -> minnesota            | count=   56 | total=   56 | confidence=1.000
md                   -> maryland             | count=   55 | total=   55 | confidence=1.000
rajasthan            -> rj                   | count=   53 | total=   53 | confidence=1.000
ut                   -> utah                 | count=   53 | total=   53 | confidence=1.000
wa                   -> washington           | count=   52 | total=   52 | confidence=1.000
ar                   -> arkansas             | count=   50 | total=   50 | confidence=1.000
haryana              -> hr                   | count=   50 | total=   50 | confidence=1.000
wi                   -> wisconsin            | count=   50 | total=   50 | confidence=1.000
or                   -> oregon               | count=   48 | total=   48 | confidence=1.000
telangana            -> tg                   | count=   45 | total=   45 | confidence=1.000
ia                   -> iowa                 | count=   41 | total=   41 | confidence=1.000
mo                   -> missouri             | count=   40 | total=   40 | confidence=1.000
ok                   -> oklahoma             | count=   39 | total=   39 | confidence=1.000
bihar                -> br                   | count=   39 | total=   39 | confidence=1.000
ct                   -> connecticut          | count=   33 | total=   33 | confidence=1.000
karnataka            -> ka                   | count=   85 | total=   86 | confidence=0.988
delhi                -> dl                   | count=  157 | total=  162 | confidence=0.969
kerala               -> keralam              | count=   55 | total=   89 | confidence=0.618
orissa               -> odisha               | count=   33 | total=   54 | confidence=0.611

==========================================================================================
NON-GEOGRAPHIC ADDRESS CANDIDATES
==========================================================================================
terrace              -> ter                  | count=   24 | total=   24 | confidence=1.000
parkway              -> pkwy                 | count=   23 | total=   23 | confidence=1.000
lane                 -> ln                   | count=  485 | total=  491 | confidence=0.988
court                -> ct                   | count=  259 | total=  263 | confidence=0.985
trail                -> trl                  | count=   56 | total=   57 | confidence=0.982
drive                -> dr                   | count= 1073 | total= 1096 | confidence=0.979
circle               -> cir                  | count=  125 | total=  128 | confidence=0.977
road                 -> rd                   | count= 1153 | total= 1182 | confidence=0.975
place                -> pl                   | count=  113 | total=  116 | confidence=0.974
avenue               -> ave                  | count=  806 | total=  832 | confidence=0.969
boulevard            -> blvd                 | count=   70 | total=   77 | confidence=0.909
street               -> st                   | count= 1017 | total= 1150 | confidence=0.884
highway              -> hwy                  | count=   27 | total=   33 | confidence=0.818

# complete data abbrevation detection

In [16]:

# ============================================================
# STEP 7
# FULL 7.6M-PAIR TOKEN TRANSITION STATISTICS
# ============================================================

# We normalize only for LEARNING the dictionary.
#
# Rules:
#   1. lowercase
#   2. NFKC
#   3. remove periods so L.L.C. can become LLC-like
#   4. turn remaining punctuation into spaces
#   5. split into tokens
#
# We only compare records having the same number of tokens.

con.execute("DROP TABLE IF EXISTS token_transition_stats")


query = """
CREATE TEMP TABLE token_transition_stats AS

WITH comparable AS (

    SELECT
        s1_name,
        matched_name,
        s1_address,
        matched_address,

        -- Remove dots first.
        -- This allows L.L.C. to be treated as LLC-like text.
        regexp_split_to_array(
            trim(
                regexp_replace(
                    regexp_replace(
                        lower(s1_name),
                        '\\.',
                        '',
                        'g'
                    ),
                    '[^[:alnum:]]+',
                    ' ',
                    'g'
                )
            ),
            ' '
        ) AS name_a,

        regexp_split_to_array(
            trim(
                regexp_replace(
                    regexp_replace(
                        lower(matched_name),
                        '\\.',
                        '',
                        'g'
                    ),
                    '[^[:alnum:]]+',
                    ' ',
                    'g'
                )
            ),
            ' '
        ) AS name_b,

        regexp_split_to_array(
            trim(
                regexp_replace(
                    regexp_replace(
                        lower(s1_address),
                        '\\.',
                        '',
                        'g'
                    ),
                    '[^[:alnum:]]+',
                    ' ',
                    'g'
                )
            ),
            ' '
        ) AS addr_a,

        regexp_split_to_array(
            trim(
                regexp_replace(
                    regexp_replace(
                        lower(matched_address),
                        '\\.',
                        '',
                        'g'
                    ),
                    '[^[:alnum:]]+',
                    ' ',
                    'g'
                )
            ),
            ' '
        ) AS addr_b

    FROM matched_records

    WHERE
        s1_name IS NOT NULL
        AND matched_name IS NOT NULL
        AND s1_address IS NOT NULL
        AND matched_address IS NOT NULL
),

name_aligned AS (

    SELECT
        'business_name' AS field,
        z[1] AS old_token,
        z[2] AS new_token
    FROM comparable,
    UNNEST(list_zip(name_a, name_b)) AS t(z)
    WHERE
        length(name_a) = length(name_b)
),

address_aligned AS (

    SELECT
        'business_address' AS field,
        z[1] AS old_token,
        z[2] AS new_token
    FROM comparable,
    UNNEST(list_zip(addr_a, addr_b)) AS t(z)
    WHERE
        length(addr_a) = length(addr_b)
)

SELECT
    field,
    old_token,
    new_token,
    COUNT(*) AS count
FROM (
    SELECT * FROM name_aligned
    UNION ALL
    SELECT * FROM address_aligned
)
WHERE
    old_token IS NOT NULL
    AND new_token IS NOT NULL
GROUP BY
    field,
    old_token,
    new_token
"""

print("Running full transition analysis...")
con.execute(query)

print("Done.")

Running full transition analysis...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Done.

In [17]:
display(
    con.execute("""
        SELECT
            field,
            old_token,
            new_token,
            count
        FROM token_transition_stats
        WHERE old_token <> new_token
        ORDER BY count DESC
        LIMIT 100
    """).fetchdf()
)

               field    old_token new_token   count
0   business_address       street        st  175622
1   business_address         road        rd  169914
2   business_address        drive        dr  163877
3      business_name      limited       ltd  151167
4   business_address       avenue       ave  129605
..               ...          ...       ...     ...
95  business_address      terrace       ter    4293
96  business_address        south     delhi    4267
97     business_name  corporation      corp    4263
98  business_address           fl     floor    4224
99  business_address       orissa        od    4110

[100 rows x 4 columns]

In [18]:
# ============================================================
# STEP 8
# CALCULATE FULL-DATA TOKEN TRANSITION CONFIDENCE
# ============================================================

confidence_df = con.execute("""
    WITH totals AS (
        SELECT
            field,
            old_token,
            SUM(count) AS total_occurrences
        FROM token_transition_stats
        GROUP BY
            field,
            old_token
    ),

    ranked AS (
        SELECT
            t.field,
            t.old_token,
            t.new_token,
            t.count,
            totals.total_occurrences,

            t.count * 1.0
                / totals.total_occurrences AS confidence,

            ROW_NUMBER() OVER (
                PARTITION BY t.field, t.old_token
                ORDER BY t.count DESC
            ) AS rn

        FROM token_transition_stats t

        JOIN totals
            ON t.field = totals.field
            AND t.old_token = totals.old_token

        WHERE
            t.old_token <> t.new_token
    )

    SELECT
        field,
        old_token,
        new_token,
        count,
        total_occurrences,
        confidence

    FROM ranked

    WHERE rn = 1

    ORDER BY
        field,
        confidence DESC,
        count DESC
""").fetchdf()

print("Candidates:", len(confidence_df))

display(
    confidence_df[
        confidence_df["count"] >= 100
    ].head(100)
)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Candidates: 308433

,field,old_token,new_token,count,total_occurrences,confidence
95218,business_address,ks,kansas,12603,31612.0,0.398678
95219,business_address,wy,wyoming,2019,5086.0,0.396972
95220,business_address,mo,missouri,20175,50998.0,0.395604
95225,business_address,or,oregon,23509,60315.0,0.389770
95229,business_address,ma,massachusetts,39356,101369.0,0.388245
...,...,...,...,...,...,...
152945,business_address,seventh,7th,112,654.0,0.171254
152951,business_address,13th,thirteenth,794,4655.0,0.170569
152961,business_address,atlanta,atl,1121,6602.0,0.169797
152966,business_address,charlotte,north,1982,11738.0,0.168853
160847,business_address,bengal,wb,6287,37814.0,0.166261

In [20]:
# ============================================================
# STEP 9
# CONDITIONAL TRANSFORMATION CONFIDENCE
#
# Confidence asks:
#
# "When old_token changes, how often does it become new_token?"
#
# We EXCLUDE old_token -> old_token from the denominator.
# ============================================================

confidence_df = con.execute("""
    WITH changed AS (

        SELECT
            field,
            old_token,
            new_token,
            count,

            SUM(count) OVER (
                PARTITION BY field, old_token
            ) AS all_transitions

        FROM token_transition_stats

        WHERE old_token <> new_token
    ),

    ranked AS (

        SELECT
            field,
            old_token,
            new_token,
            count,
            all_transitions,

            count * 1.0
                / all_transitions AS confidence,

            ROW_NUMBER() OVER (
                PARTITION BY field, old_token
                ORDER BY count DESC
            ) AS rn

        FROM changed
    )

    SELECT
        field,
        old_token,
        new_token,
        count,
        all_transitions,
        confidence

    FROM ranked

    WHERE rn = 1

    ORDER BY
        field,
        confidence DESC,
        count DESC
""").fetchdf()


print("Candidates:", len(confidence_df))

display(
    confidence_df[
        confidence_df["count"] >= 100
    ].head(100)
)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Candidates: 308433

,field,old_token,new_token,count,all_transitions,confidence
125568,business_address,ks,kansas,12603,20175.0,0.624684
125569,business_address,wy,wyoming,2019,3248.0,0.621613
125571,business_address,mo,missouri,20175,32777.0,0.615523
125579,business_address,or,oregon,23509,38316.0,0.613556
125580,business_address,az,arizona,39989,65364.0,0.611789
...,...,...,...,...,...,...
170435,business_address,winston,salem,554,1619.0,0.342187
170445,business_address,bengal,wb,6287,18515.0,0.339563
170451,business_address,parma,cleveland,318,940.0,0.338298
170452,business_address,nc,carolina,15699,46408.0,0.338282
170453,business_address,charlotte,north,1982,5868.0,0.337764

In [30]:
# ============================================================
# STEP 9 — FULL DATA, EXACTLY ONE TOKEN DIFFERENCE
# ============================================================

con.execute("DROP TABLE IF EXISTS one_change_transitions")

query = r"""
CREATE TEMP TABLE one_change_transitions AS

WITH normalized AS (

    SELECT

        -- ==================================================
        -- BUSINESS NAME — SOURCE 1
        -- ==================================================

        regexp_split_to_array(
            trim(
                regexp_replace(
                    regexp_replace(
                        lower(coalesce(s1_name, '')),
                        '\.',
                        '',
                        'g'
                    ),
                    '[^[:alnum:]]+',
                    ' ',
                    'g'
                )
            ),
            ' '
        ) AS name_a,


        -- ==================================================
        -- BUSINESS NAME — MATCHED SOURCE
        -- ==================================================

        regexp_split_to_array(
            trim(
                regexp_replace(
                    regexp_replace(
                        lower(coalesce(matched_name, '')),
                        '\.',
                        '',
                        'g'
                    ),
                    '[^[:alnum:]]+',
                    ' ',
                    'g'
                )
            ),
            ' '
        ) AS name_b,


        -- ==================================================
        -- ADDRESS — SOURCE 1
        -- ==================================================

        regexp_split_to_array(
            trim(
                regexp_replace(
                    regexp_replace(
                        lower(coalesce(s1_address, '')),
                        '\.',
                        '',
                        'g'
                    ),
                    '[^[:alnum:]]+',
                    ' ',
                    'g'
                )
            ),
            ' '
        ) AS addr_a,


        -- ==================================================
        -- ADDRESS — MATCHED SOURCE
        -- ==================================================

        regexp_split_to_array(
            trim(
                regexp_replace(
                    regexp_replace(
                        lower(coalesce(matched_address, '')),
                        '\.',
                        '',
                        'g'
                    ),
                    '[^[:alnum:]]+',
                    ' ',
                    'g'
                )
            ),
            ' '
        ) AS addr_b

    FROM matched_records
),


-- ==========================================================
-- BUSINESS NAME
-- Keep ONLY pairs with exactly ONE changed token
-- ==========================================================

name_pairs AS (

    SELECT
        'business_name' AS field,
        z[1] AS old_token,
        z[2] AS new_token

    FROM normalized,

    UNNEST(
        list_filter(
            list_zip(name_a, name_b),
            lambda x: x[1] <> x[2]
        )
    ) AS t(z)

    WHERE
        length(name_a) = length(name_b)

        AND
        length(
            list_filter(
                list_zip(name_a, name_b),
                lambda x: x[1] <> x[2]
            )
        ) = 1
),


-- ==========================================================
-- BUSINESS ADDRESS
-- Keep ONLY pairs with exactly ONE changed token
-- ==========================================================

address_pairs AS (

    SELECT
        'business_address' AS field,
        z[1] AS old_token,
        z[2] AS new_token

    FROM normalized,

    UNNEST(
        list_filter(
            list_zip(addr_a, addr_b),
            lambda x: x[1] <> x[2]
        )
    ) AS t(z)

    WHERE
        length(addr_a) = length(addr_b)

        AND
        length(
            list_filter(
                list_zip(addr_a, addr_b),
                lambda x: x[1] <> x[2]
            )
        ) = 1
)


-- ==========================================================
-- COMBINE
-- ==========================================================

SELECT
    field,
    old_token,
    new_token,
    COUNT(*) AS count

FROM (
    SELECT * FROM name_pairs

    UNION ALL

    SELECT * FROM address_pairs
)

WHERE
    old_token <> new_token

GROUP BY
    field,
    old_token,
    new_token
"""

print("Running exact-one-token transition analysis...")

con.execute(query)

print("DONE")

Running exact-one-token transition analysis...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

DONE

In [36]:
display(
    con.execute("""
        SELECT
            field,
            old_token,
            new_token,
            count
        FROM one_change_transitions
        ORDER BY count DESC
        LIMIT 100
    """).fetchdf()
)

               field    old_token   new_token   count
0      business_name      limited         ltd  137599
1   business_address         road          rd   59021
2   business_address        drive          dr   55135
3   business_address       street          st   53949
4   business_address       avenue         ave   39901
..               ...          ...         ...     ...
95  business_address         cove          cv     722
96     business_name         care      center     708
97     business_name  association  ssociation     698
98  business_address           ak      alaska     694
99     business_name       center    services     686

[100 rows x 4 columns]

In [38]:
# ============================================================
# STEP 11 — LOAD AGGREGATED TRANSITIONS
# ============================================================
#
# one_change_transitions lives inside DuckDB.
# Fetch only this small aggregated table into Pandas.
#
# We are NOT loading the 7.6M matched records.
# ============================================================

import pandas as pd

one_change_transitions = con.execute("""
    SELECT
        field,
        old_token,
        new_token,
        count
    FROM one_change_transitions
""").fetchdf()

print("Transition rows:", len(one_change_transitions))

display(
    one_change_transitions
    .sort_values("count", ascending=False)
    .head(20)
)

Transition rows: 643313

                   field    old_token      new_token   count
361433     business_name      limited            ltd  137599
330038  business_address         road             rd   59021
49388   business_address        drive             dr   55135
591835  business_address       street             st   53949
119643  business_address       avenue            ave   39901
209882  business_address           tx          texas   39348
480885  business_address  maharashtra             mh   36028
291024     business_name          inc   incorporated   33821
269776  business_address         lane             ln   24203
602994     business_name          ltd        limited   21900
501145  business_address        delhi             dl   21600
269796  business_address           oh           ohio   20038
139736  business_address           il       illinois   17514
2          business_name          inc             nc   15921
551364  business_address           tn      tennessee   15129
19143   business_address           in        indiana   14056
310058  business_address        court             ct   13804
119661  business_address           ma  massachusetts   11975
9086    business_address      gujarat             gj   11600
179819  business_address           az        arizona   11198

In [43]:
# ============================================================
# STEP 13 — CORRECT CANONICAL PAIR CONFIDENCE
# ============================================================
#
# We treat:
#
#     short <-> long
#
# as one representation pair.
#
# Confidence:
#
#     max(direction counts)
#     ---------------------
#     both direction counts
#
# Then we choose:
#
#     short -> long
#
# as the preprocessing mapping.
# ============================================================

pairs = []

for field in ["business_name", "business_address"]:

    field_df = one_change_transitions[
        one_change_transitions["field"] == field
    ]

    pair_counts = {}

    for row in field_df.itertuples(index=False):

        a = str(row.old_token)
        b = str(row.new_token)
        count = int(row.count)

        if a == b:
            continue

        if a in FAKE_NULLS or b in FAKE_NULLS:
            continue

        key = tuple(sorted([a, b]))

        if key not in pair_counts:
            pair_counts[key] = {
                "a_to_b": 0,
                "b_to_a": 0
            }

        if a == key[0]:
            pair_counts[key]["a_to_b"] += count
        else:
            pair_counts[key]["b_to_a"] += count


    # --------------------------------------------------------
    # Convert each pair into short -> canonical
    # --------------------------------------------------------

    for (a, b), counts in pair_counts.items():

        if len(a) == len(b):
            continue

        if len(a) < len(b):
            short = a
            canonical = b

            short_to_long = counts["a_to_b"]
            long_to_short = counts["b_to_a"]

        else:
            short = b
            canonical = a

            short_to_long = counts["b_to_a"]
            long_to_short = counts["a_to_b"]


        total = short_to_long + long_to_short

        if total == 0:
            continue

        pair_confidence = max(
            short_to_long,
            long_to_short
        ) / total

        pairs.append({
            "field": field,
            "short_token": short,
            "canonical_token": canonical,
            "short_to_long_count": short_to_long,
            "long_to_short_count": long_to_short,
            "total": total,
            "pair_confidence": pair_confidence
        })


canonical_pairs = pd.DataFrame(pairs)

canonical_pairs = canonical_pairs.sort_values(
    ["pair_confidence", "total"],
    ascending=[False, False]
).reset_index(drop=True)


print("Total canonical pairs:", len(canonical_pairs))

display(
    canonical_pairs.head(100)
)

Total canonical pairs: 437800

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence
0,business_address,rd,road,0,59021,59021,1.0
1,business_address,dr,drive,0,55135,55135,1.0
2,business_address,st,street,0,53949,53949,1.0
3,business_address,ave,avenue,0,39901,39901,1.0
4,business_address,tx,texas,39348,0,39348,1.0
...,...,...,...,...,...,...,...
95,business_address,ga,georgia,429,0,429,1.0
96,business_name,nvestment,investment,0,421,421,1.0
97,business_name,center,society,0,406,406,1.0
98,business_name,t,it,0,403,403,1.0
99,business_name,privte,private,0,380,380,1.0

In [44]:
# ============================================================
# STEP 13B — CHECK KNOWN EXAMPLES
# ============================================================

examples = [
    ("business_name", "ltd", "limited"),
    ("business_name", "corp", "corporation"),
    ("business_name", "inc", "incorporated"),
    ("business_address", "st", "street"),
    ("business_address", "rd", "road"),
    ("business_address", "dr", "drive"),
    ("business_address", "ave", "avenue"),
    ("business_address", "howrah", "kolkata"),
    ("business_name", "trust", "center"),
]

for field, short, canonical in examples:

    result = canonical_pairs[
        (canonical_pairs["field"] == field) &
        (canonical_pairs["short_token"] == short) &
        (canonical_pairs["canonical_token"] == canonical)
    ]

    print(f"\n{field}: {short} -> {canonical}")

    if len(result):
        display(result)
    else:
        print("Not found")

business_name: ltd -> limited

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence
437543,business_name,ltd,limited,21900,137599,159499,0.862695

business_name: corp -> corporation

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence
437718,business_name,corp,corporation,6131,4339,10470,0.585578

business_name: inc -> incorporated

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence
6,business_name,inc,incorporated,33821,0,33821,1.0

business_address: st -> street

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence
2,business_address,st,street,0,53949,53949,1.0

business_address: rd -> road

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence
0,business_address,rd,road,0,59021,59021,1.0

business_address: dr -> drive

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence
1,business_address,dr,drive,0,55135,55135,1.0

business_address: ave -> avenue

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence
3,business_address,ave,avenue,0,39901,39901,1.0

business_address: howrah -> kolkata

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence
68,business_address,howrah,kolkata,917,0,917,1.0

business_name: trust -> center

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence
77,business_name,trust,center,661,0,661,1.0

In [45]:
# ============================================================
# STEP 14 — CLASSIFY LEARNED TOKEN PAIRS
# ============================================================

# Geographic/state tokens discovered from the data.
# These are kept separately from abbreviation mappings.

US_STATES = {
    "alabama", "alaska", "arizona", "arkansas", "california",
    "colorado", "connecticut", "delaware", "florida", "georgia",
    "hawaii", "idaho", "illinois", "indiana", "iowa",
    "kansas", "kentucky", "louisiana", "maine", "maryland",
    "massachusetts", "michigan", "minnesota", "mississippi",
    "missouri", "montana", "nebraska", "nevada",
    "newhampshire", "newjersey", "newmexico", "newyork",
    "northcarolina", "northdakota", "ohio", "oklahoma", "oregon",
    "pennsylvania", "rhodeisland", "southcarolina", "southdakota",
    "tennessee", "texas", "utah", "vermont", "virginia",
    "washington", "westvirginia", "wisconsin", "wyoming"
}

INDIA_STATES = {
    "andhrapradesh", "arunachalpradesh", "assam", "bihar",
    "chhattisgarh", "goa", "gujarat", "haryana", "himachalpradesh",
    "jharkhand", "karnataka", "kerala", "madhyapradesh",
    "maharashtra", "manipur", "meghalaya", "mizoram", "nagaland",
    "odisha", "punjab", "rajasthan", "sikkim", "tamilnadu",
    "telangana", "tripura", "uttarpradesh", "uttarakhand",
    "westbengal"
}

GEOGRAPHIC_WORDS = US_STATES | INDIA_STATES

FAKE_NULLS = {
    "",
    "null",
    "none",
    "na",
    "n/a",
    "nan",
    "nil",
    "unknown",
    "notavailable"
}


# ------------------------------------------------------------
# Classify each learned pair
# ------------------------------------------------------------

def classify_pair(row):

    short = row["short_token"]
    canonical = row["canonical_token"]

    # Fake/null representation
    if short in FAKE_NULLS or canonical in FAKE_NULLS:
        return "fake_null"

    # Geographic/state representation
    if (
        short in GEOGRAPHIC_WORDS
        or canonical in GEOGRAPHIC_WORDS
    ):
        return "geographic"

    # Otherwise it remains a generic candidate
    return "candidate"


canonical_pairs["category"] = canonical_pairs.apply(
    classify_pair,
    axis=1
)


print("CATEGORY COUNTS")
print("=" * 60)

print(
    canonical_pairs["category"]
    .value_counts()
)

CATEGORY COUNTS
============================================================
category
candidate     436001
geographic      1799
Name: count, dtype: int64

In [46]:
# ============================================================
# STEP 14B — SHOW NON-GEOGRAPHIC CANDIDATES
# ============================================================

candidates = canonical_pairs[
    (canonical_pairs["category"] == "candidate") &
    (canonical_pairs["total"] >= 100)
].copy()

print("Non-geographic candidates:", len(candidates))

display(
    candidates.sort_values(
        ["pair_confidence", "total"],
        ascending=[False, False]
    ).head(200)
)

Non-geographic candidates: 358

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence,category
0,business_address,rd,road,0,59021,59021,1.0,candidate
1,business_address,dr,drive,0,55135,55135,1.0,candidate
2,business_address,st,street,0,53949,53949,1.0,candidate
3,business_address,ave,avenue,0,39901,39901,1.0,candidate
6,business_name,inc,incorporated,33821,0,33821,1.0,candidate
...,...,...,...,...,...,...,...,...
241,business_name,llc,trading,141,0,141,1.0,candidate
242,business_name,india,services,141,0,141,1.0,candidate
243,business_name,pinnade,pinnacle,0,141,141,1.0,candidate
244,business_name,dvisory,advisory,0,140,140,1.0,candidate
245,business_name,center,specialists,0,140,140,1.0,candidate

In [47]:
# ============================================================
# STEP 15 — ABBREVIATION STRUCTURE FILTER
# ============================================================
#
# A candidate is abbreviation-like if the characters of the
# short token appear in the same order inside the canonical
# token.
#
# Examples:
#
#     st   -> street       YES
#     rd   -> road         YES
#     dr   -> drive        YES
#     ave  -> avenue       YES
#     ltd  -> limited      YES
#     inc  -> incorporated YES
#
#     howrah -> kolkata    NO
#     trust  -> center     NO
#     india  -> services   NO
#
# ============================================================

def is_subsequence(short, canonical):
    """
    Returns True if every character of short appears in
    canonical in the same order.
    """

    short = str(short)
    canonical = str(canonical)

    if len(short) >= len(canonical):
        return False

    i = 0

    for char in canonical:

        if i < len(short) and short[i] == char:
            i += 1

    return i == len(short)


# ------------------------------------------------------------
# Apply structural test
# ------------------------------------------------------------

candidates["short_is_subsequence"] = candidates.apply(
    lambda row: is_subsequence(
        row["short_token"],
        row["canonical_token"]
    ),
    axis=1
)


# ------------------------------------------------------------
# Apply additional basic conditions
# ------------------------------------------------------------

abbreviation_candidates = candidates[
    (candidates["short_is_subsequence"]) &
    (candidates["short_token"].str.len() >= 2) &
    (candidates["canonical_token"].str.len() > candidates["short_token"].str.len()) &
    (candidates["total"] >= 100) &
    (candidates["pair_confidence"] >= 0.80)
].copy()


print(
    "Structural abbreviation candidates:",
    len(abbreviation_candidates)
)


display(
    abbreviation_candidates
    .sort_values(
        ["field", "pair_confidence", "total"],
        ascending=[True, False, False]
    )
    .head(200)
)

Structural abbreviation candidates: 154

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence,category,short_is_subsequence
0,business_address,rd,road,0,59021,59021,1.000000,candidate,True
1,business_address,dr,drive,0,55135,55135,1.000000,candidate,True
2,business_address,st,street,0,53949,53949,1.000000,candidate,True
3,business_address,ave,avenue,0,39901,39901,1.000000,candidate,True
7,business_address,ln,lane,0,24203,24203,1.000000,candidate,True
...,...,...,...,...,...,...,...,...,...
342,business_name,inia,india,0,100,100,1.000000,candidate,True
343,business_name,ve,ave,0,100,100,1.000000,candidate,True
437416,business_name,state,estate,1,302,303,0.996700,candidate,True
437492,business_name,service,services,31,395,426,0.927230,candidate,True
437543,business_name,ltd,limited,21900,137599,159499,0.862695,candidate,True

In [48]:
# ============================================================
# STEP 15B — CHECK KNOWN GOOD / BAD EXAMPLES
# ============================================================

examples = [
    ("rd", "road"),
    ("dr", "drive"),
    ("st", "street"),
    ("ave", "avenue"),
    ("inc", "incorporated"),
    ("ltd", "limited"),
    ("corp", "corporation"),
    ("howrah", "kolkata"),
    ("trust", "center"),
    ("llc", "trading"),
    ("india", "services"),
]

for short, canonical in examples:

    result = candidates[
        (candidates["short_token"] == short) &
        (candidates["canonical_token"] == canonical)
    ]

    print(f"\n{short} -> {canonical}")

    if len(result):
        display(
            result[
                [
                    "field",
                    "short_token",
                    "canonical_token",
                    "total",
                    "pair_confidence",
                    "short_is_subsequence"
                ]
            ]
        )
    else:
        print("Not present")

rd -> road

,field,short_token,canonical_token,total,pair_confidence,short_is_subsequence
0,business_address,rd,road,59021,1.0,True

dr -> drive

,field,short_token,canonical_token,total,pair_confidence,short_is_subsequence
1,business_address,dr,drive,55135,1.0,True

st -> street

,field,short_token,canonical_token,total,pair_confidence,short_is_subsequence
2,business_address,st,street,53949,1.0,True

ave -> avenue

,field,short_token,canonical_token,total,pair_confidence,short_is_subsequence
3,business_address,ave,avenue,39901,1.0,True

inc -> incorporated

,field,short_token,canonical_token,total,pair_confidence,short_is_subsequence
6,business_name,inc,incorporated,33821,1.0,True

ltd -> limited

,field,short_token,canonical_token,total,pair_confidence,short_is_subsequence
437543,business_name,ltd,limited,159499,0.862695,True

corp -> corporation

,field,short_token,canonical_token,total,pair_confidence,short_is_subsequence
437718,business_name,corp,corporation,10470,0.585578,True

howrah -> kolkata

,field,short_token,canonical_token,total,pair_confidence,short_is_subsequence
68,business_address,howrah,kolkata,917,1.0,False

trust -> center

,field,short_token,canonical_token,total,pair_confidence,short_is_subsequence
77,business_name,trust,center,661,1.0,False

llc -> trading

,field,short_token,canonical_token,total,pair_confidence,short_is_subsequence
241,business_name,llc,trading,141,1.0,False

india -> services

,field,short_token,canonical_token,total,pair_confidence,short_is_subsequence
242,business_name,india,services,141,1.0,False

In [49]:
# ============================================================
# STEP 16 — BUILD FINAL LEARNED ABBREVIATION DICTIONARY
# ============================================================

MIN_COUNT = 100
MIN_CONFIDENCE = 0.80


approved = abbreviation_candidates[
    (abbreviation_candidates["total"] >= MIN_COUNT) &
    (abbreviation_candidates["pair_confidence"] >= MIN_CONFIDENCE) &
    (abbreviation_candidates["short_is_subsequence"])
].copy()


print("Approved abbreviation mappings:", len(approved))


# ------------------------------------------------------------
# Separate by field
# ------------------------------------------------------------

name_approved = approved[
    approved["field"] == "business_name"
].copy()

address_approved = approved[
    approved["field"] == "business_address"
].copy()


print()
print("Business-name mappings:", len(name_approved))
print("Address mappings:", len(address_approved))


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print("\nBUSINESS NAME")
print("=" * 70)

display(
    name_approved[
        [
            "short_token",
            "canonical_token",
            "total",
            "pair_confidence"
        ]
    ]
    .sort_values(
        ["pair_confidence", "total"],
        ascending=[False, False]
    )
)


print("\nBUSINESS ADDRESS")
print("=" * 70)

display(
    address_approved[
        [
            "short_token",
            "canonical_token",
            "total",
            "pair_confidence"
        ]
    ]
    .sort_values(
        ["pair_confidence", "total"],
        ascending=[False, False]
    )
)

Approved abbreviation mappings: 154

Business-name mappings: 121
Address mappings: 33

BUSINESS NAME
======================================================================

       short_token canonical_token   total  pair_confidence
6              inc    incorporated   33821         1.000000
11              nc             inc   15921         1.000000
46              nd             and    3053         1.000000
48       ssociates      associates    2985         1.000000
50            ndia           india    2718         1.000000
...            ...             ...     ...              ...
342           inia           india     100         1.000000
343             ve             ave     100         1.000000
437416       state          estate     303         0.996700
437492     service        services     426         0.927230
437543         ltd         limited  159499         0.862695

[121 rows x 4 columns]

BUSINESS ADDRESS
======================================================================

       short_token canonical_token  total  pair_confidence
0               rd            road  59021         1.000000
1               dr           drive  55135         1.000000
2               st          street  53949         1.000000
3              ave          avenue  39901         1.000000
7               ln            lane  24203         1.000000
8               dl           delhi  21600         1.000000
14              ct           court  13804         1.000000
31             cir          circle   6677         1.000000
35              pl           place   5811         1.000000
42            blvd       boulevard   3894         1.000000
44             trl           trail   3329         1.000000
60             hwy         highway   1457         1.000000
61             ter         terrace   1398         1.000000
67            pkwy         parkway    981         1.000000
74              cv            cove    722         1.000000
122          stret          street    295         1.000000
123            rad            road    293         1.000000
124            rod            road    291         1.000000
176             sq          square    213         1.000000
188            rdg           ridge    196         1.000000
206            atl         atlanta    175         1.000000
221          sreet          street    158         1.000000
230           drve           drive    149         1.000000
248           drie           drive    139         1.000000
264           dive           drive    131         1.000000
275          steet          street    127         1.000000
315           tpke        turnpike    112         1.000000
321          aenue          avenue    110         1.000000
338            lae            lane    102         1.000000
437421          pt           point    167         0.994012
437430          ft            fort    470         0.989362
437560          no             hno    906         0.833333
437576          mt           mount    299         0.832776

In [50]:
# ============================================================
# STEP 17 — CLASSIFY LEARNED ADDRESS VARIANTS
# ============================================================

# Standard street/address suffixes.
#
# These are NOT being learned manually.
# They are only used to identify what category a learned
# transformation belongs to.

ADDRESS_SUFFIXES = {
    "street",
    "road",
    "drive",
    "avenue",
    "lane",
    "court",
    "circle",
    "place",
    "boulevard",
    "trail",
    "highway",
    "terrace",
    "parkway",
    "cove",
    "square",
    "ridge",
    "turnpike",
    "point",
    "fort",
    "mount",
    "way",
    "alley",
    "plaza",
    "expressway",
    "junction",
    "loop",
    "route",
    "highway"
}


# ------------------------------------------------------------
# Classify every approved structural candidate
# ------------------------------------------------------------

approved = abbreviation_candidates[
    (abbreviation_candidates["total"] >= 100) &
    (abbreviation_candidates["pair_confidence"] >= 0.80) &
    (abbreviation_candidates["short_is_subsequence"])
].copy()


def classify_address_variant(row):

    canonical = row["canonical_token"]

    # -----------------------------------------------
    # Standard address suffix
    # -----------------------------------------------

    if (
        row["field"] == "business_address"
        and canonical in ADDRESS_SUFFIXES
    ):
        return "address_abbreviation"

    # -----------------------------------------------
    # Everything else for now
    # -----------------------------------------------

    return "other"


approved["variant_type"] = approved.apply(
    classify_address_variant,
    axis=1
)


print("VARIANT TYPE COUNTS")
print("=" * 60)

print(
    approved["variant_type"]
    .value_counts()
)

VARIANT TYPE COUNTS
============================================================
variant_type
other                   124
address_abbreviation     30
Name: count, dtype: int64

In [51]:
# ============================================================
# STEP 17B — ADDRESS ABBREVIATIONS
# ============================================================

address_abbreviations = approved[
    approved["variant_type"] == "address_abbreviation"
].copy()


display(
    address_abbreviations[
        [
            "short_token",
            "canonical_token",
            "total",
            "pair_confidence"
        ]
    ]
    .sort_values(
        ["pair_confidence", "total"],
        ascending=[False, False]
    )
)

       short_token canonical_token  total  pair_confidence
0               rd            road  59021         1.000000
1               dr           drive  55135         1.000000
2               st          street  53949         1.000000
3              ave          avenue  39901         1.000000
7               ln            lane  24203         1.000000
14              ct           court  13804         1.000000
31             cir          circle   6677         1.000000
35              pl           place   5811         1.000000
42            blvd       boulevard   3894         1.000000
44             trl           trail   3329         1.000000
60             hwy         highway   1457         1.000000
61             ter         terrace   1398         1.000000
67            pkwy         parkway    981         1.000000
74              cv            cove    722         1.000000
122          stret          street    295         1.000000
123            rad            road    293         1.000000
124            rod            road    291         1.000000
176             sq          square    213         1.000000
188            rdg           ridge    196         1.000000
221          sreet          street    158         1.000000
230           drve           drive    149         1.000000
248           drie           drive    139         1.000000
264           dive           drive    131         1.000000
275          steet          street    127         1.000000
315           tpke        turnpike    112         1.000000
321          aenue          avenue    110         1.000000
338            lae            lane    102         1.000000
437421          pt           point    167         0.994012
437430          ft            fort    470         0.989362
437576          mt           mount    299         0.832776

In [52]:
# ============================================================
# STEP 17C — BUSINESS NAME ABBREVIATION CANDIDATES
# ============================================================

name_abbreviations = approved[
    approved["field"] == "business_name"
].copy()


display(
    name_abbreviations[
        [
            "short_token",
            "canonical_token",
            "total",
            "pair_confidence"
        ]
    ]
    .sort_values(
        ["pair_confidence", "total"],
        ascending=[False, False]
    )
)

       short_token canonical_token   total  pair_confidence
6              inc    incorporated   33821         1.000000
11              nc             inc   15921         1.000000
46              nd             and    3053         1.000000
48       ssociates      associates    2985         1.000000
50            ndia           india    2718         1.000000
...            ...             ...     ...              ...
342           inia           india     100         1.000000
343             ve             ave     100         1.000000
437416       state          estate     303         0.996700
437492     service        services     426         0.927230
437543         ltd         limited  159499         0.862695

[121 rows x 4 columns]

In [53]:
# ============================================================
# STEP 18 — BUSINESS NAME ABBREVIATION STRUCTURE
# ============================================================

name_candidates = approved[
    approved["field"] == "business_name"
].copy()


# ------------------------------------------------------------
# Character-length features
# ------------------------------------------------------------

name_candidates["short_len"] = (
    name_candidates["short_token"].str.len()
)

name_candidates["canonical_len"] = (
    name_candidates["canonical_token"].str.len()
)

name_candidates["length_gap"] = (
    name_candidates["canonical_len"]
    - name_candidates["short_len"]
)

name_candidates["compression_ratio"] = (
    name_candidates["short_len"]
    / name_candidates["canonical_len"]
)


# ------------------------------------------------------------
# Initial abbreviation rule
#
# We want:
#
#   short token
#   AND
#   at least 2 characters shorter
#   AND
#   strong pair confidence
#
# This rejects most one-character typo variants.
# ------------------------------------------------------------

name_abbreviation_candidates = name_candidates[
    (name_candidates["short_len"] <= 4) &
    (name_candidates["length_gap"] >= 2) &
    (name_candidates["pair_confidence"] >= 0.80) &
    (name_candidates["total"] >= 100) &
    (name_candidates["short_is_subsequence"])
].copy()


print(
    "Business-name abbreviation candidates:",
    len(name_abbreviation_candidates)
)


display(
    name_abbreviation_candidates[
        [
            "short_token",
            "canonical_token",
            "short_len",
            "canonical_len",
            "total",
            "pair_confidence"
        ]
    ]
    .sort_values(
        ["pair_confidence", "total"],
        ascending=[False, False]
    )
)

Business-name abbreviation candidates: 10

,short_token,canonical_token,short_len,canonical_len,total,pair_confidence
6,inc,incorporated,3,12,33821,1.000000
70,ce,care,2,4,868,1.000000
167,ss,sons,2,4,219,1.000000
207,cr,care,2,4,173,1.000000
211,fd,fund,2,4,171,1.000000
260,inc,inc0rporated,3,12,132,1.000000
263,th,tech,2,4,131,1.000000
274,ao,agro,2,4,127,1.000000
318,fd,food,2,4,111,1.000000
437543,ltd,limited,3,7,159499,0.862695

In [54]:
# ============================================================
# STEP 18B — CHECK BUSINESS NAME RESULTS
# ============================================================

display(
    name_abbreviation_candidates[
        [
            "short_token",
            "canonical_token",
            "total",
            "pair_confidence",
            "compression_ratio"
        ]
    ]
)

       short_token canonical_token   total  pair_confidence  compression_ratio
6              inc    incorporated   33821         1.000000           0.250000
70              ce            care     868         1.000000           0.500000
167             ss            sons     219         1.000000           0.500000
207             cr            care     173         1.000000           0.500000
211             fd            fund     171         1.000000           0.500000
260            inc    inc0rporated     132         1.000000           0.250000
263             th            tech     131         1.000000           0.500000
274             ao            agro     127         1.000000           0.500000
318             fd            food     111         1.000000           0.500000
437543         ltd         limited  159499         0.862695           0.428571

In [55]:
# ============================================================
# STEP 19 — FINAL BUSINESS-NAME ABBREVIATION FILTER
# ============================================================

final_name_abbreviations = name_candidates[
    (name_candidates["short_token"].str.len() >= 3) &
    (name_candidates["canonical_token"].str.len() >= 6) &
    (name_candidates["total"] >= 100) &
    (name_candidates["pair_confidence"] >= 0.80) &
    (name_candidates["short_is_subsequence"])
].copy()


final_name_abbreviations = (
    final_name_abbreviations
    .sort_values(
        ["pair_confidence", "total"],
        ascending=[False, False]
    )
    .reset_index(drop=True)
)


print(
    "Final business-name abbreviation candidates:",
    len(final_name_abbreviations)
)


display(
    final_name_abbreviations[
        [
            "short_token",
            "canonical_token",
            "total",
            "pair_confidence"
        ]
    ]
)

Final business-name abbreviation candidates: 86

   short_token canonical_token   total  pair_confidence
0          inc    incorporated   33821         1.000000
1    ssociates      associates    2985         1.000000
2   nterprises     enterprises    1114         1.000000
3    ndustries      industries    1097         1.000000
4     nstitute       institute    1036         1.000000
..         ...             ...     ...              ...
81       pivte         private     100         1.000000
82       prvae         private     100         1.000000
83       state          estate     303         0.996700
84     service        services     426         0.927230
85         ltd         limited  159499         0.862695

[86 rows x 4 columns]

In [56]:
# ============================================================
# STEP 19B — CHECK BUSINESS-NAME MAPPINGS
# ============================================================

display(
    final_name_abbreviations[
        final_name_abbreviations["short_token"].isin([
            "inc",
            "ltd",
            "pvt",
            "corp",
            "llc",
            "co"
        ])
    ]
)

,field,short_token,canonical_token,short_to_long_count,long_to_short_count,total,pair_confidence,category,short_is_subsequence,variant_type,short_len,canonical_len,length_gap,compression_ratio
0,business_name,inc,incorporated,33821,0,33821,1.000000,candidate,True,other,3,12,9,0.250000
63,business_name,inc,inc0rporated,132,0,132,1.000000,candidate,True,other,3,12,9,0.250000
85,business_name,ltd,limited,21900,137599,159499,0.862695,candidate,True,other,3,7,4,0.428571

In [58]:
# ============================================================
# STEP 20 — FINAL STRICT DICTIONARY
# ============================================================

# ------------------------------------------------------------
# BUSINESS NAME ABBREVIATIONS
# ------------------------------------------------------------
#
# Stricter compression removes typo-like transformations.
#
# Example:
#
# inc       / incorporated = 0.25  -> KEEP
# ltd       / limited      = 0.43  -> KEEP
# privte    / private      = 0.86  -> REMOVE
# ssociates / associates   = 0.90  -> REMOVE
# state     / estate       = 0.83  -> REMOVE
# ------------------------------------------------------------

final_name_dict_df = name_candidates[
    (name_candidates["short_token"].str.len() >= 3) &
    (name_candidates["canonical_token"].str.len() >= 6) &
    (name_candidates["total"] >= 100) &
    (name_candidates["pair_confidence"] >= 0.80) &
    (name_candidates["short_is_subsequence"]) &
    (
        name_candidates["short_token"].str.len()
        /
        name_candidates["canonical_token"].str.len()
        <= 0.65
    )
].copy()


# Remove canonical forms containing digits
final_name_dict_df = final_name_dict_df[
    ~final_name_dict_df["canonical_token"].str.contains(
        r"\d",
        regex=True
    )
]


# ------------------------------------------------------------
# BUSINESS ADDRESS ABBREVIATIONS
# ------------------------------------------------------------
#
# <= 0.70 retains pkwy -> parkway
# but removes rad/rod/lae -> road/lane.
# ------------------------------------------------------------

final_address_dict_df = address_abbreviations.copy()

final_address_dict_df["compression_ratio"] = (
    final_address_dict_df["short_token"].str.len()
    /
    final_address_dict_df["canonical_token"].str.len()
)


final_address_dict_df = final_address_dict_df[
    (final_address_dict_df["total"] >= 100) &
    (final_address_dict_df["pair_confidence"] >= 0.80) &
    (final_address_dict_df["compression_ratio"] <= 0.70)
].copy()


# Remove canonical forms containing digits
final_address_dict_df = final_address_dict_df[
    ~final_address_dict_df["canonical_token"].str.contains(
        r"\d",
        regex=True
    )
]


# ------------------------------------------------------------
# CREATE PYTHON DICTIONARIES
# ------------------------------------------------------------

business_name_abbreviations = dict(
    zip(
        final_name_dict_df["short_token"],
        final_name_dict_df["canonical_token"]
    )
)

business_address_abbreviations = dict(
    zip(
        final_address_dict_df["short_token"],
        final_address_dict_df["canonical_token"]
    )
)


# ------------------------------------------------------------
# DISPLAY
# ------------------------------------------------------------

print("=" * 70)
print("FINAL BUSINESS NAME ABBREVIATIONS")
print("=" * 70)

for short, canonical in business_name_abbreviations.items():
    print(f"{short:15} -> {canonical}")

print()
print("Business-name mappings:", len(business_name_abbreviations))


print("\n" + "=" * 70)
print("FINAL BUSINESS ADDRESS ABBREVIATIONS")
print("=" * 70)

for short, canonical in business_address_abbreviations.items():
    print(f"{short:15} -> {canonical}")

print()
print("Address mappings:", len(business_address_abbreviations))

======================================================================
FINAL BUSINESS NAME ABBREVIATIONS
======================================================================
inc             -> incorporated
foods           -> foodworks
ltd             -> limited

Business-name mappings: 3

======================================================================
FINAL BUSINESS ADDRESS ABBREVIATIONS
======================================================================
rd              -> road
dr              -> drive
st              -> street
ave             -> avenue
ln              -> lane
ct              -> court
cir             -> circle
pl              -> place
blvd            -> boulevard
trl             -> trail
hwy             -> highway
ter             -> terrace
pkwy            -> parkway
cv              -> cove
sq              -> square
rdg             -> ridge
tpke            -> turnpike
pt              -> point
ft              -> fort
mt              -> mount

Address mappings: 20

In [61]:
# ============================================================
# STEP 20B — INSTALL + VERIFY RAPIDFUZZ
# ============================================================

!pip install -q rapidfuzz

from rapidfuzz.distance import Levenshtein

print("RapidFuzz imported successfully")
print("Test distance:", Levenshtein.distance("stret", "street"))

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 28.4 MB/s eta 0:00:0000:0100:01
RapidFuzz imported successfully
Test distance: 1

In [62]:
# ============================================================
# STEP 21A — LEARN TYPO / SPELLING VARIANTS
# ============================================================

from rapidfuzz.distance import Levenshtein


# ------------------------------------------------------------
# Start from ALL canonical pairs.
#
# We deliberately do NOT start only from abbreviation_candidates
# because typo variants were previously filtered out.
# ------------------------------------------------------------

typo_candidates = canonical_pairs.copy()


# ------------------------------------------------------------
# Calculate edit distance
# ------------------------------------------------------------

typo_candidates["edit_distance"] = typo_candidates.apply(
    lambda row: Levenshtein.distance(
        str(row["short_token"]),
        str(row["canonical_token"])
    ),
    axis=1
)


# ------------------------------------------------------------
# Length ratio
# ------------------------------------------------------------

typo_candidates["length_ratio"] = (
    typo_candidates["short_token"].str.len()
    /
    typo_candidates["canonical_token"].str.len()
)


# ------------------------------------------------------------
# TYPO RULE
#
# We want:
#
# edit distance <= 2
# confidence >= 0.80
# at least 100 observations
# canonical form longer than variant
#
# ------------------------------------------------------------

typo_candidates = typo_candidates[
    (typo_candidates["edit_distance"] <= 2) &
    (typo_candidates["pair_confidence"] >= 0.80) &
    (typo_candidates["total"] >= 100) &
    (
        typo_candidates["canonical_token"].str.len()
        >=
        typo_candidates["short_token"].str.len()
    )
].copy()


print(
    "Potential typo candidates:",
    len(typo_candidates)
)


display(
    typo_candidates[
        [
            "field",
            "short_token",
            "canonical_token",
            "edit_distance",
            "total",
            "pair_confidence"
        ]
    ]
    .sort_values(
        ["edit_distance", "pair_confidence", "total"],
        ascending=[True, False, False]
    )
    .head(200)
)

Potential typo candidates: 162

,field,short_token,canonical_token,edit_distance,total,pair_confidence
11,business_name,nc,inc,1,15921,1.000000
43,business_address,kerala,keralam,1,3628,1.000000
46,business_name,nd,and,1,3053,1.000000
48,business_name,ssociates,associates,1,2985,1.000000
50,business_name,ndia,india,1,2718,1.000000
...,...,...,...,...,...,...
340,business_name,pivte,private,2,100,1.000000
341,business_name,prvae,private,2,100,1.000000
437407,business_name,pc,inc,2,6652,0.999850
437408,business_name,pc,llc,2,6908,0.999566
437430,business_address,ft,fort,2,470,0.989362

In [63]:
# ============================================================
# STEP 21B — CHECK KNOWN TYPO EXAMPLES
# ============================================================

known_typos = [
    ("stret", "street"),
    ("drve", "drive"),
    ("drie", "drive"),
    ("dive", "drive"),
    ("steet", "street"),
    ("aenue", "avenue"),
    ("rad", "road"),
    ("rod", "road"),
    ("lae", "lane"),
    ("foods", "foodworks"),
    ("ssociates", "associates"),
    ("privte", "private"),
]


for short, canonical in known_typos:

    result = typo_candidates[
        (typo_candidates["short_token"] == short) &
        (typo_candidates["canonical_token"] == canonical)
    ]

    print(f"\n{short} -> {canonical}")

    if len(result):
        display(
            result[
                [
                    "field",
                    "short_token",
                    "canonical_token",
                    "edit_distance",
                    "total",
                    "pair_confidence"
                ]
            ]
        )
    else:
        print("Not selected as typo candidate")

stret -> street

,field,short_token,canonical_token,edit_distance,total,pair_confidence
122,business_address,stret,street,1,295,1.0

drve -> drive

,field,short_token,canonical_token,edit_distance,total,pair_confidence
230,business_address,drve,drive,1,149,1.0

drie -> drive

,field,short_token,canonical_token,edit_distance,total,pair_confidence
248,business_address,drie,drive,1,139,1.0

dive -> drive

,field,short_token,canonical_token,edit_distance,total,pair_confidence
264,business_address,dive,drive,1,131,1.0

steet -> street

,field,short_token,canonical_token,edit_distance,total,pair_confidence
275,business_address,steet,street,1,127,1.0

aenue -> avenue

,field,short_token,canonical_token,edit_distance,total,pair_confidence
321,business_address,aenue,avenue,1,110,1.0

rad -> road

,field,short_token,canonical_token,edit_distance,total,pair_confidence
123,business_address,rad,road,1,293,1.0

rod -> road

,field,short_token,canonical_token,edit_distance,total,pair_confidence
124,business_address,rod,road,1,291,1.0

lae -> lane

,field,short_token,canonical_token,edit_distance,total,pair_confidence
338,business_address,lae,lane,1,102,1.0

foods -> foodworks
Not selected as typo candidate

ssociates -> associates

,field,short_token,canonical_token,edit_distance,total,pair_confidence
48,business_name,ssociates,associates,1,2985,1.0

privte -> private

,field,short_token,canonical_token,edit_distance,total,pair_confidence
99,business_name,privte,private,1,380,1.0

In [67]:
# ============================================================
# STEP 21C — STRICT TYPO / SPELLING DICTIONARY
# ============================================================

# Start from the candidates discovered in Step 21A.
# We intentionally make this conservative.

final_typo_candidates = typo_candidates[
    # Only one-character edits
    (typo_candidates["edit_distance"] == 1) &

    # Strong evidence from matched entities
    (typo_candidates["pair_confidence"] >= 0.80) &
    (typo_candidates["total"] >= 100) &

    # Avoid tiny tokens such as:
    # nc -> inc
    # nd -> and
    # pc -> inc
    (typo_candidates["short_token"].str.len() >= 4) &

    # The typo should be reasonably close in length
    (
        typo_candidates["length_ratio"] >= 0.80
    ) &

    # Canonical spelling should not be shorter
    (
        typo_candidates["canonical_token"].str.len()
        >=
        typo_candidates["short_token"].str.len()
    )
].copy()


# ------------------------------------------------------------
# Remove geographic tokens
# ------------------------------------------------------------

final_typo_candidates = final_typo_candidates[
    ~(
        final_typo_candidates["short_token"].isin(
            GEOGRAPHIC_WORDS
        )
        |
        final_typo_candidates["canonical_token"].isin(
            GEOGRAPHIC_WORDS
        )
    )
].copy()


# ------------------------------------------------------------
# Remove anything already classified as an abbreviation
# ------------------------------------------------------------

existing_abbreviation_pairs = set()

for short, canonical in business_name_abbreviations.items():
    existing_abbreviation_pairs.add(
        ("business_name", short, canonical)
    )

for short, canonical in business_address_abbreviations.items():
    existing_abbreviation_pairs.add(
        ("business_address", short, canonical)
    )


final_typo_candidates = final_typo_candidates[
    ~final_typo_candidates.apply(
        lambda row:
            (
                row["field"],
                row["short_token"],
                row["canonical_token"]
            )
            in existing_abbreviation_pairs,
        axis=1
    )
].copy()


# ------------------------------------------------------------
# Final display
# ------------------------------------------------------------

print(
    "FINAL TYPO CANDIDATES:",
    len(final_typo_candidates)
)

display(
    final_typo_candidates[
        [
            "field",
            "short_token",
            "canonical_token",
            "edit_distance",
            "length_ratio",
            "total",
            "pair_confidence"
        ]
    ]
    .sort_values(
        ["field", "total"],
        ascending=[True, False]
    )
)

FINAL TYPO CANDIDATES: 94

,field,short_token,canonical_token,edit_distance,length_ratio,total,pair_confidence
122,business_address,stret,street,1,0.833333,295,1.0
221,business_address,sreet,street,1,0.833333,158,1.0
230,business_address,drve,drive,1,0.800000,149,1.0
248,business_address,drie,drive,1,0.800000,139,1.0
264,business_address,dive,drive,1,0.800000,131,1.0
...,...,...,...,...,...,...,...
328,business_name,dvertising,advertising,1,0.909091,106,1.0
331,business_name,rban,urban,1,0.800000,105,1.0
332,business_name,specialist,specialists,1,0.909091,105,1.0
337,business_name,physician,physicians,1,0.900000,103,1.0
342,business_name,inia,india,1,0.800000,100,1.0

In [68]:
# ============================================================
# STEP 21D — TYPO SANITY CHECK
# ============================================================

known_cases = [
    ("stret", "street"),
    ("drve", "drive"),
    ("drie", "drive"),
    ("dive", "drive"),
    ("steet", "street"),
    ("aenue", "avenue"),
    ("rad", "road"),
    ("rod", "road"),
    ("lae", "lane"),

    # These should NOT be accepted
    ("nc", "inc"),
    ("nd", "and"),
    ("pc", "inc"),
    ("pc", "llc"),
    ("kerala", "keralam"),
]


for short, canonical in known_cases:

    result = final_typo_candidates[
        (final_typo_candidates["short_token"] == short) &
        (final_typo_candidates["canonical_token"] == canonical)
    ]

    status = "KEEP" if len(result) else "REJECT"

    print(
        f"{short:10} -> {canonical:12} {status}"
    )

stret      -> street       KEEP
drve       -> drive        KEEP
drie       -> drive        KEEP
dive       -> drive        KEEP
steet      -> street       KEEP
aenue      -> avenue       KEEP
rad        -> road         REJECT
rod        -> road         REJECT
lae        -> lane         REJECT
nc         -> inc          REJECT
nd         -> and          REJECT
pc         -> inc          REJECT
pc         -> llc          REJECT
kerala     -> keralam      REJECT

In [69]:
# ============================================================
# STEP 21E — PRECISION-FIRST TYPO CANDIDATES
# ============================================================
#
# IMPORTANT:
# These mappings are NOT applied to preprocessing yet.
#
# F0.5 favors precision, so we only identify candidates first.
# ============================================================

# Start from typo_candidates generated in STEP 21A.

tier2_typo_candidates = typo_candidates[
    # Exactly one character difference
    (typo_candidates["edit_distance"] == 1) &

    # Strong evidence from matched entities
    (typo_candidates["pair_confidence"] >= 0.95) &

    # Enough observations
    (typo_candidates["total"] >= 100) &

    # Avoid extremely short tokens
    (typo_candidates["short_token"].str.len() >= 4) &

    # Similar length — characteristic of a typo,
    # not a normal abbreviation
    (typo_candidates["length_ratio"] >= 0.75) &

    # Canonical spelling should not be shorter
    (
        typo_candidates["canonical_token"].str.len()
        >=
        typo_candidates["short_token"].str.len()
    )
].copy()


# ------------------------------------------------------------
# Remove geographic transformations
# ------------------------------------------------------------

tier2_typo_candidates = tier2_typo_candidates[
    ~(
        tier2_typo_candidates["short_token"].isin(GEOGRAPHIC_WORDS)
        |
        tier2_typo_candidates["canonical_token"].isin(GEOGRAPHIC_WORDS)
    )
].copy()


# ------------------------------------------------------------
# Remove mappings already classified as abbreviations
# ------------------------------------------------------------

tier2_typo_candidates = tier2_typo_candidates[
    ~tier2_typo_candidates.apply(
        lambda row:
            (
                row["field"],
                row["short_token"],
                row["canonical_token"]
            )
            in existing_abbreviation_pairs,
        axis=1
    )
].copy()


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print(
    "Tier-2 typo candidates:",
    len(tier2_typo_candidates)
)

display(
    tier2_typo_candidates[
        [
            "field",
            "short_token",
            "canonical_token",
            "edit_distance",
            "length_ratio",
            "total",
            "pair_confidence"
        ]
    ]
    .sort_values(
        ["pair_confidence", "total"],
        ascending=[False, False]
    )
)

Tier-2 typo candidates: 93

,field,short_token,canonical_token,edit_distance,length_ratio,total,pair_confidence
48,business_name,ssociates,associates,1,0.900000,2985,1.0000
50,business_name,ndia,india,1,0.800000,2718,1.0000
63,business_name,nterprises,enterprises,1,0.909091,1114,1.0000
65,business_name,ndustries,industries,1,0.900000,1097,1.0000
66,business_name,nstitute,institute,1,0.888889,1036,1.0000
...,...,...,...,...,...,...,...
331,business_name,rban,urban,1,0.800000,105,1.0000
332,business_name,specialist,specialists,1,0.909091,105,1.0000
337,business_name,physician,physicians,1,0.900000,103,1.0000
342,business_name,inia,india,1,0.800000,100,1.0000
437416,business_name,state,estate,1,0.833333,303,0.9967

In [70]:
# ============================================================
# STEP 21F — TOP TIER-2 TYPO CANDIDATES
# ============================================================

display(
    tier2_typo_candidates[
        [
            "field",
            "short_token",
            "canonical_token",
            "total",
            "pair_confidence",
            "length_ratio"
        ]
    ]
    .head(200)
)

,field,short_token,canonical_token,total,pair_confidence,length_ratio
48,business_name,ssociates,associates,2985,1.0000,0.900000
50,business_name,ndia,india,2718,1.0000,0.800000
63,business_name,nterprises,enterprises,1114,1.0000,0.909091
65,business_name,ndustries,industries,1097,1.0000,0.900000
66,business_name,nstitute,institute,1036,1.0000,0.888889
...,...,...,...,...,...,...
331,business_name,rban,urban,105,1.0000,0.800000
332,business_name,specialist,specialists,105,1.0000,0.909091
337,business_name,physician,physicians,103,1.0000,0.900000
342,business_name,inia,india,100,1.0000,0.800000
437416,business_name,state,estate,303,0.9967,0.833333

In [72]:
# ============================================================
# STEP 21F-B — CHECK KNOWN CASES
# ============================================================

known_cases = [
    ("stret", "street"),
    ("drve", "drive"),
    ("drie", "drive"),
    ("dive", "drive"),
    ("steet", "street"),
    ("aenue", "avenue"),
    ("rad", "road"),
    ("rod", "road"),
    ("lae", "lane"),
]

for short, canonical in known_cases:

    result = tier2_typo_candidates[
        (tier2_typo_candidates["short_token"] == short) &
        (tier2_typo_candidates["canonical_token"] == canonical)
    ]

    print(
        f"{short:10} -> {canonical:10}",
        "CANDIDATE" if len(result) else "NOT SELECTED"
    )

stret      -> street     CANDIDATE
drve       -> drive      CANDIDATE
drie       -> drive      CANDIDATE
dive       -> drive      CANDIDATE
steet      -> street     CANDIDATE
aenue      -> avenue     CANDIDATE
rad        -> road       NOT SELECTED
rod        -> road       NOT SELECTED
lae        -> lane       NOT SELECTED

In [73]:
# ============================================================
# STEP 22 — CREATE NORMALIZATION DICTIONARIES
# ============================================================

import json


# ------------------------------------------------------------
# Tier 1: high-confidence abbreviations
# ------------------------------------------------------------

tier1 = {
    "business_name": business_name_abbreviations,
    "business_address": business_address_abbreviations
}


# ------------------------------------------------------------
# Tier 2: learned spelling/typo candidates
#
# NOT applied yet.
# ------------------------------------------------------------

tier2 = {}

for field in ["business_name", "business_address"]:

    field_df = tier2_typo_candidates[
        tier2_typo_candidates["field"] == field
    ]

    tier2[field] = dict(
        zip(
            field_df["short_token"],
            field_df["canonical_token"]
        )
    )


# ------------------------------------------------------------
# Combined object
# ------------------------------------------------------------

normalization_rules = {
    "tier1_abbreviations": tier1,
    "tier2_typos": tier2
}


# ------------------------------------------------------------
# Save JSON
# ------------------------------------------------------------

JSON_PATH = "/kaggle/working/abbreviations.json"

with open(JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(
        normalization_rules,
        f,
        ensure_ascii=False,
        indent=2
    )


print("Saved:", JSON_PATH)

print(
    "Tier 1 name rules:",
    len(tier1["business_name"])
)

print(
    "Tier 1 address rules:",
    len(tier1["business_address"])
)

print(
    "Tier 2 name typo rules:",
    len(tier2["business_name"])
)

print(
    "Tier 2 address typo rules:",
    len(tier2["business_address"])
)

Saved: /kaggle/working/abbreviations.json
Tier 1 name rules: 3
Tier 1 address rules: 20
Tier 2 name typo rules: 86
Tier 2 address typo rules: 7

In [74]:
# ============================================================
# STEP 22B — INSPECT SAVED JSON
# ============================================================

with open(JSON_PATH, "r", encoding="utf-8") as f:
    rules = json.load(f)

print(json.dumps(rules, ensure_ascii=False, indent=2))

{
  "tier1_abbreviations": {
    "business_name": {
      "inc": "incorporated",
      "foods": "foodworks",
      "ltd": "limited"
    },
    "business_address": {
      "rd": "road",
      "dr": "drive",
      "st": "street",
      "ave": "avenue",
      "ln": "lane",
      "ct": "court",
      "cir": "circle",
      "pl": "place",
      "blvd": "boulevard",
      "trl": "trail",
      "hwy": "highway",
      "ter": "terrace",
      "pkwy": "parkway",
      "cv": "cove",
      "sq": "square",
      "rdg": "ridge",
      "tpke": "turnpike",
      "pt": "point",
      "ft": "fort",
      "mt": "mount"
    }
  },
  "tier2_typos": {
    "business_name": {
      "ssociates": "associates",
      "ndia": "india",
      "nterprises": "enterprises",
      "ndustries": "industries",
      "nstitute": "institute",
      "nternational": "international",
      "cademy": "academy",
      "lliance": "alliance",
      "ssociation": "association",
      "nvestments": "investments",
      "ngineering": "engineering",
      "dvisors": "advisors",
      "nitiative": "initiative",
      "nfrastructure": "infrastructure",
      "nergy": "energy",
      "nion": "union",
      "nvestment": "investment",
      "privte": "private",
      "associate": "associates",
      "prvate": "private",
      "nfra": "infra",
      "priate": "private",
      "privae": "private",
      "nkle": "ankle",
      "ducation": "education",
      "partner": "partners",
      "ndocrinology": "endocrinology",
      "nnovations": "innovations",
      "xports": "exports",
      "nfotech": "infotech",
      "nited": "united",
      "lectronics": "electronics",
      "merican": "american",
      "ssets": "assets",
      "nnovative": "innovative",
      "ntegrated": "integrated",
      "lite": "elite",
      "tlantic": "atlantic",
      "mpire": "empire",
      "xpress": "express",
      "mpex": "impex",
      "pivate": "private",
      "quity": "equity",
      "solution": "solutions",
      "nsurance": "insurance",
      "nalytics": "analytics",
      "system": "systems",
      "nvironmental": "environmental",
      "llied": "allied",
      "dvanced": "advanced",
      "nchor": "anchor",
      "nterests": "interests",
      "nified": "unified",
      "nterstate": "interstate",
      "ducational": "educational",
      "food": "foods",
      "ntertainment": "entertainment",
      "srael": "israel",
      "nimal": "animal",
      "ptimal": "optimal",
      "ndustrial": "industrial",
      "pparel": "apparel",
      "brother": "brothers",
      "sset": "asset",
      "ffice": "office",
      "erospace": "aerospace",
      "lectric": "electric",
      "ntelligence": "intelligence",
      "utomotive": "automotive",
      "dvisory": "advisory",
      "gricultural": "agricultural",
      "venture": "ventures",
      "utomation": "automation",
      "consultant": "consultants",
      "trader": "traders",
      "lley": "alley",
      "nteriors": "interiors",
      "manuel": "emanuel",
      "product": "products",
      "ngineers": "engineers",
      "dvertising": "advertising",
      "rban": "urban",
      "specialist": "specialists",
      "physician": "physicians",
      "inia": "india",
      "state": "estate"
    },
    "business_address": {
      "stret": "street",
      "sreet": "street",
      "drve": "drive",
      "drie": "drive",
      "dive": "drive",
      "steet": "street",
      "aenue": "avenue"
    }
  }
}

In [76]:
# ============================================================
# STEP 22.5 — FINAL SAFE PRODUCTION ABBREVIATIONS
# ============================================================

# ============================================================
# 1. BUSINESS NAME ABBREVIATIONS
# ============================================================

LEGAL_NAME_CANONICALS = {
    "incorporated",
    "limited",
    "corporation",
    "private",
    "company",
    "llc",
    "llp",
    "plc"
}


safe_name_df = name_candidates[
    # Strong evidence
    (name_candidates["total"] >= 100) &
    (name_candidates["pair_confidence"] >= 0.80) &

    # Must actually be shorter
    (
        name_candidates["short_token"].str.len()
        <
        name_candidates["canonical_token"].str.len()
    ) &

    # Subsequence structure
    (name_candidates["short_is_subsequence"]) &

    # Canonical must be a legitimate legal/business term
    (
        name_candidates["canonical_token"].isin(
            LEGAL_NAME_CANONICALS
        )
    ) &

    # IMPORTANT:
    # Require real compression.
    #
    # inc/incorporated = 0.25
    # ltd/limited      = 0.43
    #
    # privte/private   = 0.86  -> rejected
    #
    (
        name_candidates["short_token"].str.len()
        /
        name_candidates["canonical_token"].str.len()
        <= 0.65
    )
].copy()


# ------------------------------------------------------------
# Build name dictionary
# ------------------------------------------------------------

production_name_abbreviations = dict(
    zip(
        safe_name_df["short_token"],
        safe_name_df["canonical_token"]
    )
)


# ============================================================
# 2. BUSINESS ADDRESS ABBREVIATIONS
# ============================================================

# IMPORTANT:
# Use ONLY the address-abbreviation dataframe generated
# before typo candidates were mixed in.

safe_address_df = address_abbreviations[
    (address_abbreviations["total"] >= 100) &
    (address_abbreviations["pair_confidence"] >= 0.80)
].copy()


# ------------------------------------------------------------
# Compression ratio
# ------------------------------------------------------------

safe_address_df["compression_ratio"] = (
    safe_address_df["short_token"].str.len()
    /
    safe_address_df["canonical_token"].str.len()
)


# ------------------------------------------------------------
# Keep genuine abbreviations
#
# rd  -> road       0.50
# dr  -> drive      0.40
# st  -> street     0.33
# ave -> avenue     0.50
# pkwy -> parkway   0.67
#
# Reject:
#
# stret -> street   0.83
# rad   -> road     0.75
# drve  -> drive    0.80
# ------------------------------------------------------------

safe_address_df = safe_address_df[
    safe_address_df["compression_ratio"] <= 0.70
].copy()


# ------------------------------------------------------------
# Build address dictionary
# ------------------------------------------------------------

production_address_abbreviations = dict(
    zip(
        safe_address_df["short_token"],
        safe_address_df["canonical_token"]
    )
)


# ============================================================
# DISPLAY FINAL PRODUCTION RULES
# ============================================================

print("=" * 70)
print("FINAL PRODUCTION BUSINESS NAME ABBREVIATIONS")
print("=" * 70)

for short, canonical in production_name_abbreviations.items():
    print(f"{short:15} -> {canonical}")

print(
    "\nBusiness-name rules:",
    len(production_name_abbreviations)
)


print("\n" + "=" * 70)
print("FINAL PRODUCTION BUSINESS ADDRESS ABBREVIATIONS")
print("=" * 70)

for short, canonical in production_address_abbreviations.items():
    print(f"{short:15} -> {canonical}")

print(
    "\nAddress rules:",
    len(production_address_abbreviations)
)

======================================================================
FINAL PRODUCTION BUSINESS NAME ABBREVIATIONS
======================================================================
inc             -> incorporated
ltd             -> limited

Business-name rules: 2

======================================================================
FINAL PRODUCTION BUSINESS ADDRESS ABBREVIATIONS
======================================================================
rd              -> road
dr              -> drive
st              -> street
ave             -> avenue
ln              -> lane
ct              -> court
cir             -> circle
pl              -> place
blvd            -> boulevard
trl             -> trail
hwy             -> highway
ter             -> terrace
pkwy            -> parkway
cv              -> cove
sq              -> square
rdg             -> ridge
tpke            -> turnpike
pt              -> point
ft              -> fort
mt              -> mount

Address rules: 20

In [77]:
# ============================================================
# STEP 22.6 — SAVE FINAL PRODUCTION DICTIONARY
# ============================================================

import json

production_rules = {
    "business_name": production_name_abbreviations,
    "business_address": production_address_abbreviations
}

PRODUCTION_JSON = "/kaggle/working/abbreviations_production.json"

with open(PRODUCTION_JSON, "w", encoding="utf-8") as f:
    json.dump(
        production_rules,
        f,
        ensure_ascii=False,
        indent=2
    )

print("Saved:", PRODUCTION_JSON)

print("\nFinal production dictionary:")
print(
    json.dumps(
        production_rules,
        ensure_ascii=False,
        indent=2
    )
)

Saved: /kaggle/working/abbreviations_production.json

Final production dictionary:
{
  "business_name": {
    "inc": "incorporated",
    "ltd": "limited"
  },
  "business_address": {
    "rd": "road",
    "dr": "drive",
    "st": "street",
    "ave": "avenue",
    "ln": "lane",
    "ct": "court",
    "cir": "circle",
    "pl": "place",
    "blvd": "boulevard",
    "trl": "trail",
    "hwy": "highway",
    "ter": "terrace",
    "pkwy": "parkway",
    "cv": "cove",
    "sq": "square",
    "rdg": "ridge",
    "tpke": "turnpike",
    "pt": "point",
    "ft": "fort",
    "mt": "mount"
  }
}

In [78]:
import os

print(
    "Exists:",
    os.path.exists(PRODUCTION_JSON)
)

print(
    "Size:",
    os.path.getsize(PRODUCTION_JSON),
    "bytes"
)

Exists: True
Size: 509 bytes

In [96]:
%%writefile -a /kaggle/working/src/preprocess.py

# ============================================================
# Learned abbreviation system
# ============================================================

import json
from pathlib import Path

ABBREVIATION_JSON = (
    Path(__file__).resolve().parent.parent
    / "abbreviations_production.json"
)


def load_abbreviation_rules():
    """
    Load production abbreviation mappings learned from
    the training data.
    """
    with open(ABBREVIATION_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


ABBREVIATION_RULES = load_abbreviation_rules()

BUSINESS_NAME_ABBREVIATIONS = ABBREVIATION_RULES.get(
    "business_name", {}
)

BUSINESS_ADDRESS_ABBREVIATIONS = ABBREVIATION_RULES.get(
    "business_address", {}
)


def apply_abbreviations(text, mapping):
    """
    Apply token-level abbreviation replacements.

    Only complete tokens are replaced, so substrings inside
    normal words are not accidentally modified.
    """
    if not text or not mapping:
        return text

    # Longer tokens first
    tokens = sorted(mapping.keys(), key=len, reverse=True)

    for token in tokens:
        replacement = mapping[token]

        pattern = rf"\b{re.escape(token)}\b"

        text = re.sub(
            pattern,
            replacement,
            text
        )

    return text

Appending to /kaggle/working/src/preprocess.py

In [97]:
with open("/kaggle/working/src/preprocess.py", "r", encoding="utf-8") as f:
    content = f.read()

print("Abbreviation system added:", "apply_abbreviations" in content)
print("File size:", len(content), "characters")

Abbreviation system added: True
File size: 7695 characters

In [98]:
%%writefile -a /kaggle/working/src/preprocess.py

# ============================================================
# Normalization using learned abbreviation mappings
# ============================================================

def normalize_business_name(text):
    """
    Normalize business names using learned production
    abbreviation mappings.
    """
    text = normalize_unicode(text)

    if not text:
        return ""

    # Lowercase while preserving Unicode
    text = text.lower()

    # Apply learned business-name abbreviations
    text = apply_abbreviations(
        text,
        BUSINESS_NAME_ABBREVIATIONS
    )

    # '&' -> 'and'
    text = text.replace("&", " and ")

    # Remove punctuation while preserving Unicode
    cleaned = []

    for char in text:
        category = unicodedata.category(char)

        if category.startswith("P"):
            cleaned.append(" ")
        else:
            cleaned.append(char)

    text = "".join(cleaned)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


def normalize_business_address(text):
    """
    Normalize business addresses using learned production
    abbreviation mappings.
    """
    text = normalize_unicode(text)

    if not text:
        return ""

    # Lowercase while preserving Unicode
    text = text.lower()

    # Apply learned address abbreviations
    text = apply_abbreviations(
        text,
        BUSINESS_ADDRESS_ABBREVIATIONS
    )

    # '&' -> 'and'
    text = text.replace("&", " and ")

    # Remove punctuation while preserving Unicode
    cleaned = []

    for char in text:
        category = unicodedata.category(char)

        if category.startswith("P"):
            cleaned.append(" ")
        else:
            cleaned.append(char)

    text = "".join(cleaned)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

Appending to /kaggle/working/src/preprocess.py

In [99]:
import sys

if "preprocess" in sys.modules:
    del sys.modules["preprocess"]

sys.path.insert(0, "/kaggle/working/src")

import preprocess

print("preprocess.py loaded successfully")

preprocess.py loaded successfully

In [100]:
# ============================================================
# Test learned abbreviation preprocessing
# ============================================================

name_tests = [
    "ABC Inc",
    "ABC Inc.",
    "ABC Ltd",
    "ABC LTD.",
    "ABC Incorporated",
    "ABC Limited",
    "R&D Inc",
    "राम मार्केटिंग प्राइवेट लिमिटेड",
    "L'Oréal & Sons",
]

address_tests = [
    "123 Main St",
    "456 Oak Rd",
    "789 Park Ave",
    "100 Lake Dr",
    "25 Central Pkwy",
    "59 St. John's Rd.",
    "13 Rue Fermat",
    "7 Rue Masséna",
]

print("BUSINESS NAME TESTS")
print("=" * 60)

for text in name_tests:
    print(f"{text:40} -> {preprocess.normalize_business_name(text)}")


print("\nBUSINESS ADDRESS TESTS")
print("=" * 60)

for text in address_tests:
    print(f"{text:40} -> {preprocess.normalize_business_address(text)}")

BUSINESS NAME TESTS
============================================================
ABC Inc                                  -> abc incorporated
ABC Inc.                                 -> abc incorporated
ABC Ltd                                  -> abc limited
ABC LTD.                                 -> abc limited
ABC Incorporated                         -> abc incorporated
ABC Limited                              -> abc limited
R&D Inc                                  -> r and d incorporated
राम मार्केटिंग प्राइवेट लिमिटेड          -> राम मार्केटिंग प्राइवेट लिमिटेड
L'Oréal & Sons                           -> l oréal and sons

BUSINESS ADDRESS TESTS
============================================================
123 Main St                              -> 123 main street
456 Oak Rd                               -> 456 oak road
789 Park Ave                             -> 789 park avenue
100 Lake Dr                              -> 100 lake drive
25 Central Pkwy                          -> 25 central parkway
59 St. John's Rd.                        -> 59 street john s road
13 Rue Fermat                            -> 13 rue fermat
7 Rue Masséna                            -> 7 rue masséna

In [101]:
negative_tests = [
    "Trust Center",
    "PC LLC",
    "Foods Foodworks",
    "Private Business",
    "123 Stret Road",
    "456 Rad Drive",
    "789 Rod Lane",
    "100 Lae Street",
]

print("NEGATIVE / REJECTED MAPPING TESTS")
print("=" * 70)

for text in negative_tests:
    result_name = preprocess.normalize_business_name(text)
    result_address = preprocess.normalize_business_address(text)

    print(f"\nOriginal : {text}")
    print(f"Name     : {result_name}")
    print(f"Address  : {result_address}")

NEGATIVE / REJECTED MAPPING TESTS
======================================================================

Original : Trust Center
Name     : trust center
Address  : trust center

Original : PC LLC
Name     : pc llc
Address  : pc llc

Original : Foods Foodworks
Name     : foods foodworks
Address  : foods foodworks

Original : Private Business
Name     : private business
Address  : private business

Original : 123 Stret Road
Name     : 123 stret road
Address  : 123 stret road

Original : 456 Rad Drive
Name     : 456 rad drive
Address  : 456 rad drive

Original : 789 Rod Lane
Name     : 789 rod lane
Address  : 789 rod lane

Original : 100 Lae Street
Name     : 100 lae street
Address  : 100 lae street

In [102]:
# ============================================================
# Real-data integration test
# ============================================================

import pandas as pd
import sys

# Make sure our current preprocess.py is loaded
if "preprocess" in sys.modules:
    del sys.modules["preprocess"]

sys.path.insert(0, "/kaggle/working/src")
import preprocess

train_path = (
    "/kaggle/input/datasets/lakshaygauniyal/"
    "amazon-ml-2026-dataset/"
    "6ab10eb3b23ba_student_resource/student_resource/"
    "dataset/train/train_source1.tsv"
)

df_sample = pd.read_csv(
    train_path,
    sep="\t",
    nrows=20
)

print("Original shape:", df_sample.shape)
print("\nOriginal columns:")
print(df_sample.columns.tolist())

processed_sample = preprocess.preprocess_dataframe(df_sample)

print("\nProcessed columns:")
print(processed_sample.columns.tolist())

print("\nSample:")
print(
    processed_sample[
        [
            "business_name",
            "business_name_clean",
            "business_address",
            "business_address_clean",
            "address_numbers"
        ]
    ].head(10).to_string(index=False)
)

Original shape: (20, 4)

Original columns:
['entity_id', 'business_name', 'business_address', 'country']

Processed columns:
['entity_id', 'business_name', 'business_address', 'country', 'business_name_clean', 'business_address_clean', 'address_numbers']

Sample:
                           business_name                      business_name_clean                                                                                                          business_address                                                                                            business_address_clean address_numbers
                     Orelee's Barbershop                      orelee s barbershop                                                                                    1795 Westchester Drive, High Point, NC                                                                              1795 westchester drive high point nc          [1795]
                             Prime Money                              prime money                                                                                           17560 Ellis Road, Tahlequah, OK                                                                                     17560 ellis road tahlequah ok         [17560]
                           B+ Retail Inc                   b+ retail incorporated                                                                                       1712 Montebello Avenue, Phoenix, AZ                                                                                 1712 montebello avenue phoenix az          [1712]
                           Christ Chapel                            christ chapel                                                                         2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD                                                                    2100 cameron drive unit apartment g dundalk md          [2100]
                 Prabhav Business Center                  prabhav business center                                                                      797, Lake Town Block A, Kolkata, Howrah, West Bengal                                                                  797 lake town block a kolkata howrah west bengal           [797]
              Custom Wealth Services LLC               custom wealth services llc                                                                                         OH, Columbus, 5559 Orville Avenue                                                                                   oh columbus 5559 orville avenue          [5559]
Consulting Nyasa Nursing Private Limited consulting nyasa nursing private limited 2505, Tower 1, Oakwood, Runwal Greens, Mulund Goreagon Link Road, Near Fortis Hospital, Bhandup West, Mumbai, Maharashtra 2505 tower 1 oakwood runwal greens mulund goreagon link road near fortis hospital bhandup west mumbai maharashtra       [2505, 1]
                       Nexus Anchor Rain                        nexus anchor rain                                                                              1111 Church Street, Unit 2007, Nashville, TN                                                                         1111 church street unit 2007 nashville tn    [1111, 2007]
                       Moore Bitwise Inc               moore bitwise incorporated                                                                                     337 Oakland Avenue, Michigan City, IN                                                                               337 oakland avenue michigan city in           [337]
              Dermatology Green Medicine               dermatology green medicine                                                               294 Meadowcreek Drive, Unit Unit 2, Village Of Pewaukee, WI                                                          294 meadowcreek drive unit unit 2 village of pewaukee wi        [294, 2]